// Code generated by lipc; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"os"

	"lipalpha/runtime"
)

type Dependency struct {
	Kind string
	Spec string
}

func RequiredDependencies() []Dependency { return []Dependency{} }

func parseCLIInputs(args []string) (map[string]runtime.Value, error) {
	inputs, err := runtime.ParseCLIInputs(args, []runtime.Input{{Name: "input", Type: "number"}})
	if err != nil {
		return nil, fmt.Errorf("%w\nusage: %s <input:number>", err, os.Args[0])
	}
	return inputs, nil
}

func buildGraph(host runtime.Host) *runtime.Graph {
	host = host.Clone()
	g := runtime.NewGraph()
	g.Add(runtime.NodeSpec{Name: "valid", Op: "", Pure: true, Deps: []string{"input"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary(">", values["input"], runtime.Value(float64(0)))
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}})
	g.Add(runtime.NodeSpec{Name: "doubled", Op: "", Pure: true, Deps: []string{"input"}, Gates: []string{"valid"}, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("*", values["input"], runtime.Value(float64(2)))
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}, Gate: func(values map[string]runtime.Value) (bool, error) {
		ok, err := runtime.Bool(values["valid"])
		if err != nil {
			return false, err
		}
		if !ok {
			return false, nil
		}
		return true, nil
	}})
	g.Add(runtime.NodeSpec{Name: "__return_0", Op: "", Pure: true, Deps: []string{"doubled"}, Gates: []string{"valid"}, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return runtime.Ready(values["doubled"])
	}, Gate: func(values map[string]runtime.Value) (bool, error) {
		ok, err := runtime.Bool(values["valid"])
		if err != nil {
			return false, err
		}
		if !ok {
			return false, nil
		}
		return true, nil
	}, Output: true, ValueType: "number"})
	return g
}

func checkInputUpdates(inputs map[string]runtime.Value) error {
	for name, value := range inputs {
		_ = value
		switch name {
		case "input":
			if err := runtime.CheckType(value, "number"); err != nil {
				return fmt.Errorf("input input: %w", err)
			}
		default:
			return fmt.Errorf("unknown flow input %q", name)
		}
	}
	return nil
}

func checkInputs(inputs map[string]runtime.Value) error {
	if _, ok := inputs["input"]; !ok {
		return fmt.Errorf("missing flow input input")
	}
	return checkInputUpdates(inputs)
}

func checkHost(host runtime.Host) error {
	return nil
}

type Instance struct{ engine *runtime.Instance }

func NewInstance(host runtime.Host, inputs map[string]runtime.Value) (*Instance, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, err
	}
	graph := buildGraph(host)
	return &Instance{engine: graph.NewInstance(host, inputs)}, nil
}

func (i *Instance) Tick(ctx context.Context, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if i == nil || i.engine == nil {
		return nil, nil, fmt.Errorf("nil flow instance")
	}
	if err := checkInputUpdates(inputs); err != nil {
		return nil, nil, err
	}
	return i.engine.Tick(ctx, inputs)
}

func (i *Instance) SetState(name string, value runtime.Value) error {
	if i == nil || i.engine == nil {
		return fmt.Errorf("nil flow instance")
	}
	return i.engine.SetState(name, value)
}

func (i *Instance) State(name string) (runtime.Value, bool) {
	if i == nil || i.engine == nil {
		return nil, false
	}
	return i.engine.State(name)
}

func (i *Instance) TickCount() uint64 {
	if i == nil || i.engine == nil {
		return 0
	}
	return i.engine.TickCount()
}

func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunAuto(ctx, host, inputs)
}

func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).Run(ctx, inputs)
}

func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunParallel(ctx, host, inputs, limit)
}

func main() {
	ctx := context.Background()
	host := runtime.DefaultHost()
	inputs := map[string]runtime.Value{}
	parsed, err := parseCLIInputs(os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}
	inputs = parsed
	value, trace, err := Run(ctx, host, inputs)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		for _, event := range trace {
			fmt.Fprintf(os.Stderr, "%s %s %s\n", event.Node, event.Status, event.Reason)
		}
		os.Exit(1)
	}
	output, err := runtime.FormatValue(value)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println(output)
}
