// Code generated by lipc; DO NOT EDIT.
// LIP 0.6.4
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"lipalpha/runtime"
)

type Dependency struct {
	Kind  string
	Spec  string
	Alias string
}

func RequiredDependencies() []Dependency { return []Dependency{} }

func parseCLIInputs(args []string) (map[string]runtime.Value, error) {
	inputs, err := runtime.ParseCLIInputs(args, []runtime.Input{{Name: "input", Type: "number"}})
	if err != nil {
		return nil, fmt.Errorf("%w\nusage: %s <input:number>", err, os.Args[0])
	}
	return inputs, nil
}

func buildGraph(host runtime.Host) *runtime.Graph {
	host = host.Clone()
	g := runtime.NewGraphWithOptions(runtime.GraphOptions{ReleaseIntermediates: true})
	g.Add(runtime.NodeSpec{Name: "valid", Op: "", Effect: runtime.EffectPure, Deps: []string{"input"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary(">", values["input"], runtime.Value(float64(0)))
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}})
	g.Add(runtime.NodeSpec{Name: "__match_0", Op: "", Effect: runtime.EffectPure, Deps: []string{"valid"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		_ = values["valid"]
		var value0 runtime.Value
		value1 := false
		if !value1 {
			value2 := false
			value3, err := runtime.Binary("==", values["valid"], runtime.Value(true))
			if err != nil {
				return runtime.Failed(err)
			}
			value4, err := runtime.Bool(value3)
			if err != nil {
				return runtime.Failed(err)
			}
			if value4 {
				value2 = true
			}
			if value2 {
				value0 = runtime.Value(float64(0))
				value1 = true
			}
		}
		if !value1 {
			value5 := false
			value6, err := runtime.Binary("==", values["valid"], runtime.Value(false))
			if err != nil {
				return runtime.Failed(err)
			}
			value7, err := runtime.Bool(value6)
			if err != nil {
				return runtime.Failed(err)
			}
			if value7 {
				value5 = true
			}
			if value5 {
				value0 = runtime.Value(float64(1))
				value1 = true
			}
		}
		if !value1 {
			return runtime.Failed(fmt.Errorf("non-exhaustive match"))
		}
		return runtime.Ready(value0)
	}})
	g.Add(runtime.NodeSpec{Name: "__gate_0", Op: "", Effect: runtime.EffectPure, Deps: []string{"__match_0"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("==", values["__match_0"], runtime.Value(float64(0)))
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}})
	g.Add(runtime.NodeSpec{Name: "doubled", Op: "", Effect: runtime.EffectPure, Deps: []string{"input"}, Gates: []string{"__gate_0"}, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("*", values["input"], runtime.Value(float64(2)))
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}, Gate: func(values map[string]runtime.Value) (bool, error) {
		ok0, err := runtime.Bool(values["__gate_0"])
		if err != nil {
			return false, err
		}
		if !ok0 {
			return false, nil
		}
		return true, nil
	}})
	g.Add(runtime.NodeSpec{Name: "__return_0", Op: "", Effect: runtime.EffectPure, Deps: []string{"doubled"}, Gates: []string{"__gate_0"}, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return runtime.Ready(values["doubled"])
	}, Gate: func(values map[string]runtime.Value) (bool, error) {
		ok0, err := runtime.Bool(values["__gate_0"])
		if err != nil {
			return false, err
		}
		if !ok0 {
			return false, nil
		}
		return true, nil
	}, Output: true, ValueType: "number?"})
	g.Add(runtime.NodeSpec{Name: "__gate_1", Op: "", Effect: runtime.EffectPure, Deps: []string{"__match_0"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("==", values["__match_0"], runtime.Value(float64(1)))
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}})
	return g
}

func checkInputUpdates(inputs map[string]runtime.Value) error {
	for name, value := range inputs {
		_ = value
		switch name {
		case "input":
			if err := runtime.CheckType(value, "number"); err != nil {
				return fmt.Errorf("input input: %w", err)
			}
		default:
			return fmt.Errorf("unknown flow input %q", name)
		}
	}
	return nil
}

func checkInputs(inputs map[string]runtime.Value) error {
	if _, ok := inputs["input"]; !ok {
		return fmt.Errorf("missing flow input input")
	}
	return checkInputUpdates(inputs)
}

func checkHost(host runtime.Host) error {
	return nil
}

type Instance struct{ engine *runtime.Instance }

func NewInstance(host runtime.Host, inputs map[string]runtime.Value) (*Instance, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, err
	}
	graph := buildGraph(host)
	return &Instance{engine: graph.NewInstance(host, inputs)}, nil
}

func (i *Instance) Tick(ctx context.Context, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if i == nil || i.engine == nil {
		return nil, nil, fmt.Errorf("nil flow instance")
	}
	if err := checkInputUpdates(inputs); err != nil {
		return nil, nil, err
	}
	return i.engine.Tick(ctx, inputs)
}

func (i *Instance) SetState(name string, value runtime.Value) error {
	if i == nil || i.engine == nil {
		return fmt.Errorf("nil flow instance")
	}
	return i.engine.SetState(name, value)
}

func (i *Instance) State(name string) (runtime.Value, bool) {
	if i == nil || i.engine == nil {
		return nil, false
	}
	return i.engine.State(name)
}

func (i *Instance) TickCount() uint64 {
	if i == nil || i.engine == nil {
		return 0
	}
	return i.engine.TickCount()
}

func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunAuto(ctx, host, inputs)
}

func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).Run(ctx, inputs)
}

func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunParallel(ctx, host, inputs, limit)
}

func executionError(err error, trace []runtime.TraceEvent) error {
	message, context := err.Error(), ""
	for _, event := range trace {
		if event.Status != runtime.Error {
			continue
		}
		switch event.Node {
		case "valid":
			message = "examples/gated.lip:2:5: " + event.Reason
			context = "\n  2 |     valid = input > 0\n    |     ^"
		case "__match_0":
			message = "examples/gated.lip:3:5: " + event.Reason
			context = "\n  3 |     match valid {\n    |     ^"
		case "__gate_0":
			message = "examples/gated.lip:4:9: " + event.Reason
			context = "\n  4 |         true => {\n    |         ^"
		case "doubled":
			message = "examples/gated.lip:5:13: " + event.Reason
			context = "\n  5 |             doubled = input * 2\n    |             ^"
		case "__return_0":
			message = "examples/gated.lip:6:13: " + event.Reason
			context = "\n  6 |             return doubled\n    |             ^"
		case "__gate_1":
			message = "examples/gated.lip:8:9: " + event.Reason
			context = "\n  8 |         false => {}\n    |         ^"
		}
		break
	}
	if line, column, found := runtime.SourcePosition(err); found {
		switch fmt.Sprintf("%d:%d", line, column) {
		}
	}
	if hint := runtime.ExecutionHint(err); hint != "" {
		context += "\n  hint: " + hint
	}
	return fmt.Errorf("%s%s", message, context)
}

func main() { os.Exit(runMain()) }

func runMain() int {
	inputs, err := parseCLIInputs(os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 2
	}
	_ = inputs
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	host := runtime.DefaultHost()
	value, trace, err := Run(ctx, host, inputs)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", executionError(err, trace))
		return 1
	}
	output, err := runtime.FormatValue(value)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	fmt.Println(output)
	return 0
}
