// Code generated by lipc; DO NOT EDIT.
// LIP 0.6.4
package mixedflow

import (
	"context"
	"fmt"

	"lipalpha/runtime"
)

type Dependency struct {
	Kind  string
	Spec  string
	Alias string
}

func RequiredDependencies() []Dependency {
	return []Dependency{{Kind: "host", Spec: "load_text"}, {Kind: "python", Spec: "math"}}
}

func __lip_fn_parse(host runtime.Host) runtime.Op {
	return func(ctx context.Context, args []runtime.Value) runtime.Result {
		ctx, err := runtime.EnterFunction(ctx)
		if err != nil {
			return runtime.Failed(err)
		}
		if len(args) != 1 {
			return runtime.Failed(fmt.Errorf("function parse expects 1 arguments, got %d", len(args)))
		}
		if err := runtime.CheckType(args[0], "string"); err != nil {
			return runtime.Failed(fmt.Errorf("argument text: %w", err))
		}
		value0, err := runtime.StringCall(ctx, "string.parse_number", []runtime.Value{args[0]})
		if err != nil {
			return runtime.Failed(err)
		}
		if err := runtime.CheckType(value0, "number"); err != nil {
			return runtime.Failed(fmt.Errorf("function parse result: %w", err))
		}
		return runtime.Ready(value0)
	}
}

func __lip_fn_render(host runtime.Host) runtime.Op {
	return func(ctx context.Context, args []runtime.Value) runtime.Result {
		ctx, err := runtime.EnterFunction(ctx)
		if err != nil {
			return runtime.Failed(err)
		}
		if len(args) != 1 {
			return runtime.Failed(fmt.Errorf("function render expects 1 arguments, got %d", len(args)))
		}
		if err := runtime.CheckType(args[0], "number"); err != nil {
			return runtime.Failed(fmt.Errorf("argument value: %w", err))
		}
		if err := runtime.CheckType(runtime.StringValue(args[0]), "string"); err != nil {
			return runtime.Failed(fmt.Errorf("function render result: %w", err))
		}
		return runtime.Ready(runtime.StringValue(args[0]))
	}
}

func buildGraph(host runtime.Host) *runtime.Graph {
	host = host.Clone()
	g := runtime.NewGraphWithOptions(runtime.GraphOptions{ReleaseIntermediates: true})
	host.RegisterPure("__lip_fn_parse", __lip_fn_parse(host))
	host.RegisterPure("__lip_fn_render", __lip_fn_render(host))
	g.Add(runtime.NodeSpec{Name: "text", Op: "load_text", Effect: host.EffectsOf([]string{"load_text"}), Deps: []string{"path"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "load_text", []runtime.Value{values["path"]})
	}})
	g.Add(runtime.NodeSpec{Name: "values", Op: "list.map", Effect: runtime.EffectPure, Deps: []string{"text"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.StringCall(ctx, "string.split_whitespace", []runtime.Value{values["text"]})
		if err != nil {
			return runtime.Failed(err)
		}
		value1 := runtime.Op(func(ctx context.Context, value2 []runtime.Value) runtime.Result {
			return host.Call(ctx, "__lip_fn_parse", value2)
		})
		value3, err := runtime.ListCall(ctx, "list.map", []runtime.Value{value0}, value1)
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value3)
	}})
	g.Add(runtime.NodeSpec{Name: "roots", Effect: host.EffectsOf([]string{"math.sqrt"}), Deps: []string{"values"}, Gates: nil, Map: &runtime.MapSpec{Source: "values", Ops: []string{"math.sqrt"}, Eval: func(ctx context.Context, item runtime.Value, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "math.sqrt", []runtime.Value{item})
	}}})
	g.Add(runtime.NodeSpec{Name: "__return_0", Op: "", Effect: runtime.EffectPure, Deps: []string{"roots"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0 := map[string]runtime.Value{}
		value0["roots"] = values["roots"]
		value1, err := runtime.ListCall(ctx, "list.sum", []runtime.Value{values["roots"]}, nil)
		if err != nil {
			return runtime.Failed(err)
		}
		value0["total"] = value1
		value2 := runtime.Op(func(ctx context.Context, value3 []runtime.Value) runtime.Result {
			return host.Call(ctx, "__lip_fn_render", value3)
		})
		value4, err := runtime.ListCall(ctx, "list.map", []runtime.Value{values["roots"]}, value2)
		if err != nil {
			return runtime.Failed(err)
		}
		value5, err := runtime.StringCall(ctx, "string.join", []runtime.Value{value4, runtime.Value(", ")})
		if err != nil {
			return runtime.Failed(err)
		}
		value0["label"] = value5
		return runtime.Ready(value0)
	}, Output: true, ValueType: "object"})
	return g
}

func checkInputUpdates(inputs map[string]runtime.Value) error {
	for name, value := range inputs {
		_ = value
		switch name {
		case "path":
			if err := runtime.CheckType(value, "string"); err != nil {
				return fmt.Errorf("input path: %w", err)
			}
		default:
			return fmt.Errorf("unknown flow input %q", name)
		}
	}
	return nil
}

func checkInputs(inputs map[string]runtime.Value) error {
	if _, ok := inputs["path"]; !ok {
		return fmt.Errorf("missing flow input path")
	}
	return checkInputUpdates(inputs)
}

func checkHost(host runtime.Host) error {
	if err := host.RequireOperation("load_text"); err != nil {
		return err
	}
	return nil
}

type Instance struct{ engine *runtime.Instance }

func NewInstance(host runtime.Host, inputs map[string]runtime.Value) (*Instance, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, err
	}
	graph := buildGraph(host)
	return &Instance{engine: graph.NewInstance(host, inputs)}, nil
}

func (i *Instance) Tick(ctx context.Context, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if i == nil || i.engine == nil {
		return nil, nil, fmt.Errorf("nil flow instance")
	}
	if err := checkInputUpdates(inputs); err != nil {
		return nil, nil, err
	}
	return i.engine.Tick(ctx, inputs)
}

func (i *Instance) SetState(name string, value runtime.Value) error {
	if i == nil || i.engine == nil {
		return fmt.Errorf("nil flow instance")
	}
	return i.engine.SetState(name, value)
}

func (i *Instance) State(name string) (runtime.Value, bool) {
	if i == nil || i.engine == nil {
		return nil, false
	}
	return i.engine.State(name)
}

func (i *Instance) TickCount() uint64 {
	if i == nil || i.engine == nil {
		return 0
	}
	return i.engine.TickCount()
}

func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunAuto(ctx, host, inputs)
}

func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).Run(ctx, inputs)
}

func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunParallel(ctx, host, inputs, limit)
}
