;;; emacs.el --- LIP editor integration tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'lip-mode)
(setq lipc-command (getenv "LIP_TEST_COMPILER"))
(setq lip-enable-flymake nil)

(defun lip-test--position (word)
  (goto-char (point-min))
  (search-forward word)
  (- (point) (length word)))

(ert-deftest lip-mode-filetype-and-syntax ()
  (with-temp-buffer
    (setq buffer-file-name "example.lip")
    (set-auto-mode)
    (should (eq major-mode 'lip-mode))
    (insert-file-contents (getenv "LIP_EDITOR_EXAMPLE"))
    (font-lock-ensure)
    (should (eq (get-text-property (lip-test--position "match") 'face) 'font-lock-keyword-face))
    (should (eq (get-text-property (lip-test--position "双倍") 'face) 'font-lock-function-name-face))
    (should (eq (get-text-property (lip-test--position "continue") 'face) 'font-lock-keyword-face))
    (should (eq (get-text-property (+ (lip-test--position "mapped: list.map") 8) 'face) 'font-lock-builtin-face))
    (should (eq (get-text-property (+ (lip-test--position "trimmed: string.trim") 9) 'face) 'font-lock-builtin-face))
    (should (eq (get-text-property (lip-test--position "list.map().") 'face) 'font-lock-comment-face))
    (should (eq (get-text-property (lip-test--position "list.map()\"") 'face) 'font-lock-string-face))
    (let ((position (lip-test--position "运行 # // */")))
      (should (nth 3 (syntax-ppss (+ position 4))))
      (should-not (nth 4 (syntax-ppss (+ position 4)))))
    (let ((position (lip-test--position "floor: 7 // 2")))
      (should-not (nth 4 (syntax-ppss (+ position 10)))))
    (let ((position (lip-test--position "logarithm: 8 */ 2")))
      (should-not (nth 4 (syntax-ppss (+ position 14)))))
    (should-not (eq (get-text-property (lip-test--position "when =") 'face) 'font-lock-keyword-face))))

(ert-deftest lip-mode-indentation-and-completion ()
  (with-temp-buffer
    (lip-mode)
    (insert-file-contents (getenv "LIP_EDITOR_EXAMPLE"))
    (let ((expected (buffer-string)))
      (goto-char (point-min))
      (while (re-search-forward "^ +" nil t) (replace-match ""))
      (indent-region (point-min) (point-max))
      (should (equal expected (buffer-string)))
      (indent-region (point-min) (point-max))
      (should (equal expected (buffer-string))))
    (erase-buffer)
    (insert "fn 双倍(值: number) { 值 * 2 }\nlist.ma")
    (let ((completion (lip-completion-at-point)))
      (should (equal (buffer-substring-no-properties (nth 0 completion) (nth 1 completion)) "list.ma"))
      (should (equal (sort (all-completions "list.ma" (nth 2 completion)) #'string<) '("list.map" "list.max")))
      (should (member "双倍" (nth 2 completion))))))

(ert-deftest lip-flymake-unsaved-unicode-and-cleanup ()
  (with-temp-buffer
    (lip-mode)
    (insert-file-contents (getenv "LIP_EDITOR_BAD"))
    (let ((expected (json-read-file (getenv "LIP_EDITOR_EXPECTED")))
          (response :pending))
      (lip-flymake (lambda (diagnostics &rest _) (setq response diagnostics)))
      (let ((deadline (+ (float-time) 10)))
        (while (and (eq response :pending) (< (float-time) deadline))
          (accept-process-output nil 0.05)))
      (should (listp response))
      (should (= (length response) 1))
      (let ((diagnostic (car response)))
        (should (= (flymake-diagnostic-beg diagnostic) (1+ (alist-get 'character_offset expected))))
        (should (string-match-p "LIP_" (flymake-diagnostic-text diagnostic))))
      (should-not lip--check-process)
      ;; Check changed buffer contents without saving the file.
      (erase-buffer)
      (insert "flow Fixed() -> number { return 7 }")
      (setq response :pending)
      (lip-flymake (lambda (diagnostics &rest _) (setq response diagnostics)))
      (let ((deadline (+ (float-time) 10)))
        (while (and (eq response :pending) (< (float-time) deadline))
          (accept-process-output nil 0.05)))
      (should (null response))
      (should-not (cl-find-if (lambda (buffer) (string-match-p " \\*lip-flymake" (buffer-name buffer))) (buffer-list))))))

(ert-deftest lip-flymake-cancel-and-stale-response ()
  (let ((lipc-command (getenv "LIP_TEST_SLOW_COMPILER"))
        (responses nil))
    (with-temp-buffer
      (lip-mode)
      (insert "flow Bad() -> number { return missing }")
      (lip-flymake (lambda (&rest items) (push (cons 'old items) responses)))
      (let* ((process lip--check-process)
             (temporary (car (last (process-command process))))
             (output (process-buffer process)))
        (erase-buffer)
        (insert "flow Fixed() -> number { return 7 }")
        (lip-flymake (lambda (&rest items) (push (cons 'new items) responses)))
        (let ((deadline (+ (float-time) 10)))
          (while (and lip--check-process (< (float-time) deadline)) (accept-process-output nil 0.05)))
        (should (equal responses '((new nil))))
        (should-not (process-live-p process))
        (should-not (buffer-live-p output))
        (should-not (file-exists-p temporary)))
      (setq responses nil)
      (erase-buffer)
      (insert "flow Bad() -> number { return missing }")
      (lip-flymake (lambda (&rest items) (push items responses)))
      (erase-buffer)
      (insert "flow Fixed() -> number { return 7 }")
      (let ((deadline (+ (float-time) 10)))
        (while (and lip--check-process (< (float-time) deadline)) (accept-process-output nil 0.05)))
      (should-not responses))
    (let ((buffer (generate-new-buffer " *lip-test-cancel*")))
      (with-current-buffer buffer
        (lip-mode)
        (insert "flow Fixed() -> number { return 7 }")
        (lip-flymake (lambda (&rest items) (push items responses)))
        (let* ((process lip--check-process)
               (temporary (car (last (process-command process))))
               (output (process-buffer process)))
          (kill-buffer buffer)
          (accept-process-output nil 0.1)
          (should-not (process-live-p process))
          (should-not (buffer-live-p output))
          (should-not (file-exists-p temporary)))))
    (should-not responses)))

(ert-deftest lip-check-saves-and-shows-diagnostics ()
  (save-window-excursion
    (let* ((file (make-temp-file "lip check 中文 " nil ".lip"))
           (buffer (progn (copy-file (getenv "LIP_EDITOR_BAD") file t) (find-file-noselect file))))
      (unwind-protect
          (with-current-buffer buffer
            (should (eq major-mode 'lip-mode))
            (lip-check)
            (set-buffer buffer)
            (let ((deadline (+ (float-time) 10)))
              (while (and lip--check-process (< (float-time) deadline)) (accept-process-output nil 0.05)))
            (should (= (length (flymake-diagnostics)) 1))
            (erase-buffer)
            (insert "flow Fixed() -> number { return 7 }\n")
            (lip-check)
            (set-buffer buffer)
            (let ((deadline (+ (float-time) 10)))
              (while (and lip--check-process (< (float-time) deadline)) (accept-process-output nil 0.05)))
            (should-not (buffer-modified-p))
            (should-not (flymake-diagnostics))
            (should (equal (with-temp-buffer
                             (insert-file-contents file) (buffer-string))
                           (buffer-string))))
        (kill-buffer buffer)
        (delete-file file)))))

(ert-run-tests-batch-and-exit)
