-- Integration tests run with Neovim's Lua API, independently of the Vim package.
local function tests()
  local env = vim.env
  vim.opt.runtimepath:prepend(env.LIP_EDITOR_NEOVIM)
  vim.cmd('filetype plugin indent on')
  vim.cmd('syntax enable')
  vim.cmd('runtime plugin/lip.lua')
  local lip = require('lip')
  lip.setup({ compiler = env.LIP_TEST_COMPILER })
  vim.cmd.edit(vim.fn.fnameescape(env.LIP_EDITOR_EXAMPLE))
  local function equal(expected, actual)
    assert(vim.deep_equal(expected, actual), 'expected ' .. vim.inspect(expected) .. ', got ' .. vim.inspect(actual))
  end
  local function group(line, word)
    local text = vim.api.nvim_buf_get_lines(0, line - 1, line, false)[1]
    local column = assert(text:find(word, 1, true))
    return vim.fn.synIDattr(vim.fn.synID(line, column, 1), 'name')
  end
  equal('lip', vim.bo.filetype)
  equal('lip', vim.b.current_syntax)
  equal('# %s', vim.bo.commentstring)
  equal("v:lua.require'lip'.complete", vim.bo.omnifunc)
  equal(4, vim.bo.shiftwidth)
  for _, item in ipairs({ {6, 'match'}, {10, 'continue'}, {11, 'break'} }) do
    equal('lipKeyword', group(item[1], item[2]))
  end
  for _, item in ipairs({ {19, '//'}, {20, '*/'}, {21, '**'} }) do
    equal('lipOperator', group(item[1], item[2]))
  end
  equal('lipNumber', group(23, '1.25e-2'))
  equal('lipComment', group(4, '#'))
  equal('lipString', group(12, '#'))
  equal('lipString', group(12, '//'))
  equal('lipString', group(12, '{}'))
  equal('lipString', group(12, 'list.map'))
  equal('lipComment', group(4, 'list.map'))
  equal('lipBuiltin', group(24, 'list.map'))
  equal('lipBuiltin', group(25, 'string.trim'))
  assert(group(5, 'when') ~= 'lipKeyword')
  equal({ 'list.map', 'list.max' }, lip.complete(0, 'list.ma'))
  assert(vim.tbl_contains(lip.complete(0, '双'), '双倍'))
  local expected = vim.api.nvim_buf_get_lines(0, 0, -1, false)
  vim.cmd('syntax off')
  vim.api.nvim_buf_set_lines(0, 0, -1, false, vim.tbl_map(function(line) return (line:gsub('^ *', '')) end, expected))
  vim.cmd('normal! gg=G')
  equal(expected, vim.api.nvim_buf_get_lines(0, 0, -1, false))
  vim.cmd('syntax enable')
  equal('lipKeyword', group(6, 'match'))
  vim.cmd('normal! gg=G')
  equal(expected, vim.api.nvim_buf_get_lines(0, 0, -1, false))

  vim.cmd('edit! ' .. vim.fn.fnameescape(env.LIP_EDITOR_BAD))
  local buf = vim.api.nvim_get_current_buf()
  vim.cmd('LipCheck')
  assert(vim.wait(10000, function() return not lip.is_checking(buf) end, 10), 'compiler timed out')
  local items = vim.diagnostic.get(buf, { namespace = lip.namespace })
  equal(1, #items)
  local wanted = vim.json.decode(table.concat(vim.fn.readfile(env.LIP_EDITOR_EXPECTED), '\n'))
  equal(wanted.line - 1, items[1].lnum)
  equal(wanted.byte_column - 1, items[1].col)
  assert(items[1].message:match('LIP_'))
  -- Cancelling an older asynchronous check must not overwrite a newer result.
  lip.setup({ compiler = env.LIP_TEST_SLOW_COMPILER })
  lip.check(buf)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, { 'flow Fixed() -> number { return 7 }' })
  lip.check(buf)
  assert(vim.wait(10000, function() return not lip.is_checking(buf) end, 10))
  equal({}, vim.diagnostic.get(buf, { namespace = lip.namespace }))
  -- Changed text rejects a response even before a TextChanged event is dispatched.
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, { 'flow Bad() -> number { return missing }' })
  lip.check(buf)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, { 'flow Fixed() -> number { return 7 }' })
  assert(vim.wait(10000, function() return not lip.is_checking(buf) end, 10))
  equal({}, vim.diagnostic.get(buf, { namespace = lip.namespace }))
  lip.setup({ check_on_save = true })
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, { 'flow Bad() -> number { return missing }' })
  vim.cmd('write')
  assert(vim.wait(10000, function() return not lip.is_checking(buf) end, 10))
  equal(1, #vim.diagnostic.get(buf, { namespace = lip.namespace }))
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, { 'flow Fixed() -> number { return 7 }' })
  vim.cmd('LipCheck')
  assert(vim.wait(10000, function() return not lip.is_checking(buf) end, 10))
  equal({}, vim.diagnostic.get(buf, { namespace = lip.namespace }))
  lip.check(buf)
  vim.api.nvim_buf_delete(buf, { force = true })
  assert(not lip.is_checking(buf), 'deleted buffer still owns a compiler process')
  vim.cmd('enew!')
  vim.bo.filetype = 'lip'
  vim.o.virtualedit = 'onemore'
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { '变量 = 双倍' })
  vim.api.nvim_win_set_cursor(0, { 1, #'变量 = 双倍' })
  equal(#'变量 = ', lip.complete(1, ''))
  equal({ 'list.map', 'list.max' }, vim.fn.eval("v:lua.require'lip'.complete(0, 'list.ma')"))
  vim.bo.filetype = 'text'
  assert(vim.bo.omnifunc ~= "v:lua.require'lip'.complete", 'LIP options leaked to another filetype')
  assert(not vim.api.nvim_buf_get_commands(0, {}).LipCheck)
end
local ok, err = xpcall(tests, debug.traceback)
if not ok then
  vim.fn.writefile({ err }, vim.env.LIP_EDITOR_FAILURES)
  vim.api.nvim_err_writeln(err)
  vim.cmd('cquit 1')
else
  vim.cmd('qa!')
end
