// Code generated by lipc; DO NOT EDIT.
package main

import (
	"context"
	"fmt"

	"lipalpha/runtime"
)

type Dependency struct {
	Kind string
	Spec string
}

func RequiredDependencies() []Dependency {
	return []Dependency{{Kind: "python", Spec: "numpy"}, {Kind: "python", Spec: "pandas"}}
}

func buildGraph(host runtime.Host) *runtime.Graph {
	host = host.Clone()
	g := runtime.NewGraph()
	g.Add(runtime.NodeSpec{Name: "total", Op: "numpy.sum", Effect: runtime.EffectUnknown, Deps: []string{"values"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "numpy.sum", []runtime.Value{values["values"]})
	}})
	g.Add(runtime.NodeSpec{Name: "average", Op: "numpy.mean", Effect: runtime.EffectUnknown, Deps: []string{"values"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "numpy.mean", []runtime.Value{values["values"]})
	}})
	g.Add(runtime.NodeSpec{Name: "series", Op: "pandas.Series", Effect: runtime.EffectUnknown, Deps: []string{"values"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "pandas.Series", []runtime.Value{values["values"]})
	}})
	g.Add(runtime.NodeSpec{Name: "raw_stats", Op: "python.call", Effect: runtime.EffectUnknown, Deps: []string{"series"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "python.call", []runtime.Value{values["series"], runtime.Value("describe"), []runtime.Value{}})
	}})
	g.Add(runtime.NodeSpec{Name: "stats", Op: "python.to_json", Effect: runtime.EffectUnknown, Deps: []string{"raw_stats"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "python.to_json", []runtime.Value{values["raw_stats"]})
	}})
	g.Add(runtime.NodeSpec{Name: "__expr_0", Op: "python.release", Effect: runtime.EffectUnknown, Deps: []string{"raw_stats"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "python.release", []runtime.Value{values["raw_stats"]})
	}})
	g.Add(runtime.NodeSpec{Name: "__expr_1", Op: "python.release", Effect: runtime.EffectUnknown, Deps: []string{"series"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "python.release", []runtime.Value{values["series"]})
	}})
	g.Add(runtime.NodeSpec{Name: "__return_0", Op: "", Effect: runtime.EffectPure, Deps: []string{"total", "average", "stats"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return runtime.Ready([]runtime.Value{values["total"], values["average"], values["stats"]})
	}, Output: true, ValueType: "any"})
	return g
}

func checkInputUpdates(inputs map[string]runtime.Value) error {
	for name, value := range inputs {
		_ = value
		switch name {
		case "values":
			if err := runtime.CheckType(value, "any"); err != nil {
				return fmt.Errorf("input values: %w", err)
			}
		default:
			return fmt.Errorf("unknown flow input %q", name)
		}
	}
	return nil
}

func checkInputs(inputs map[string]runtime.Value) error {
	if _, ok := inputs["values"]; !ok {
		return fmt.Errorf("missing flow input values")
	}
	return checkInputUpdates(inputs)
}

func checkHost(host runtime.Host) error {
	return nil
}

type Instance struct{ engine *runtime.Instance }

func NewInstance(host runtime.Host, inputs map[string]runtime.Value) (*Instance, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, err
	}
	graph := buildGraph(host)
	return &Instance{engine: graph.NewInstance(host, inputs)}, nil
}

func (i *Instance) Tick(ctx context.Context, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if i == nil || i.engine == nil {
		return nil, nil, fmt.Errorf("nil flow instance")
	}
	if err := checkInputUpdates(inputs); err != nil {
		return nil, nil, err
	}
	return i.engine.Tick(ctx, inputs)
}

func (i *Instance) SetState(name string, value runtime.Value) error {
	if i == nil || i.engine == nil {
		return fmt.Errorf("nil flow instance")
	}
	return i.engine.SetState(name, value)
}

func (i *Instance) State(name string) (runtime.Value, bool) {
	if i == nil || i.engine == nil {
		return nil, false
	}
	return i.engine.State(name)
}

func (i *Instance) TickCount() uint64 {
	if i == nil || i.engine == nil {
		return 0
	}
	return i.engine.TickCount()
}

func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunAuto(ctx, host, inputs)
}

func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).Run(ctx, inputs)
}

func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunParallel(ctx, host, inputs, limit)
}
