package main

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"lipalpha/compiler"
	"lipalpha/runtime"
)

func TestVersionAndCurrentDocumentation(t *testing.T) {
	root := filepath.Join("..", "..")
	data, err := os.ReadFile(filepath.Join(root, "VERSION"))
	if err != nil {
		t.Fatal(err)
	}
	if expected := strings.TrimSpace(string(data)); expected != version {
		t.Fatalf("VERSION=%s, lipc=%s", expected, version)
	}
	if version != runtime.Version {
		t.Fatalf("lipc=%s runtime=%s", version, runtime.Version)
	}
	graph, err := compiler.ParseAndBuild("print(7)")
	if err != nil {
		t.Fatal(err)
	}
	code, err := compiler.GenerateGo(graph)
	if err != nil || !strings.HasPrefix(code, "// Code generated by lipc; DO NOT EDIT.\n// LIP "+version+"\n") {
		t.Fatalf("generated version missing: %v", err)
	}
	patch := regexp.MustCompile(`[0-9]+\.[0-9]+\.[0-9]+`)
	for _, path := range []string{
		"README.md", "README.en.md", "CHANGELOG.md", "RELEASE.md", "docs/SPECS.md",
		"docs/ALPHA-0.6-SPEC.md", "docs/TUTORIAL.md", "docs/QUICKSTART.md",
		"docs/STRING-LIBRARY.md", "docs/VIBE-CODING.md", "docs/CONSISTENCY-AUDIT.md",
		"docs/LIST-LIBRARY.md", "docs/COMPILER.md", "docs/PYTHON-INTEGRATION.md",
		"docs/INTERACTIVE-LEARNING.md", "docs/VALUE-LIFETIMES.md", "docs/ROADMAP.md", "docs/EDITORS.md", "examples/PROTOTYPES.md",
	} {
		data, err := os.ReadFile(filepath.Join(root, path))
		if err != nil {
			t.Fatal(err)
		}
		// History remains intact; the first version reference identifies the
		// current implementation or newest changelog entry.
		if got := patch.FindString(string(data)); got != version {
			t.Errorf("%s identifies %q as current, want %s", path, got, version)
		}
	}
}
