// Code generated by lipc; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"lipalpha/runtime"
)

type Dependency struct {
	Kind  string
	Spec  string
	Alias string
}

func RequiredDependencies() []Dependency { return []Dependency{} }

func parseCLIInputs(args []string) (map[string]runtime.Value, error) {
	inputs, err := runtime.ParseCLIInputs(args, []runtime.Input{{Name: "input", Type: "number"}})
	if err != nil {
		return nil, fmt.Errorf("%w\nusage: %s <input:number>", err, os.Args[0])
	}
	return inputs, nil
}

func buildGraph(host runtime.Host) *runtime.Graph {
	host = host.Clone()
	g := runtime.NewGraph()
	g.Add(runtime.NodeSpec{Name: "count", Effect: runtime.EffectPure, State: true, ValueType: "number", Deps: nil, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return runtime.Ready(runtime.Value(float64(0)))
	}})
	g.Add(runtime.NodeSpec{Name: "doubled", Op: "", Effect: runtime.EffectPure, Deps: []string{"count"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("*", values["count"], runtime.Value(float64(2)))
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}})
	g.Add(runtime.NodeSpec{Name: "__return_0", Op: "", Effect: runtime.EffectPure, Deps: []string{"doubled", "input"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("+", values["doubled"], values["input"])
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}, Output: true, ValueType: "number"})
	return g
}

func checkInputUpdates(inputs map[string]runtime.Value) error {
	for name, value := range inputs {
		_ = value
		switch name {
		case "input":
			if err := runtime.CheckType(value, "number"); err != nil {
				return fmt.Errorf("input input: %w", err)
			}
		default:
			return fmt.Errorf("unknown flow input %q", name)
		}
	}
	return nil
}

func checkInputs(inputs map[string]runtime.Value) error {
	if _, ok := inputs["input"]; !ok {
		return fmt.Errorf("missing flow input input")
	}
	return checkInputUpdates(inputs)
}

func checkHost(host runtime.Host) error {
	return nil
}

type Instance struct{ engine *runtime.Instance }

func NewInstance(host runtime.Host, inputs map[string]runtime.Value) (*Instance, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, err
	}
	graph := buildGraph(host)
	return &Instance{engine: graph.NewInstance(host, inputs)}, nil
}

func (i *Instance) Tick(ctx context.Context, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if i == nil || i.engine == nil {
		return nil, nil, fmt.Errorf("nil flow instance")
	}
	if err := checkInputUpdates(inputs); err != nil {
		return nil, nil, err
	}
	return i.engine.Tick(ctx, inputs)
}

func (i *Instance) SetState(name string, value runtime.Value) error {
	if i == nil || i.engine == nil {
		return fmt.Errorf("nil flow instance")
	}
	return i.engine.SetState(name, value)
}

func (i *Instance) State(name string) (runtime.Value, bool) {
	if i == nil || i.engine == nil {
		return nil, false
	}
	return i.engine.State(name)
}

func (i *Instance) TickCount() uint64 {
	if i == nil || i.engine == nil {
		return 0
	}
	return i.engine.TickCount()
}

func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunAuto(ctx, host, inputs)
}

func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).Run(ctx, inputs)
}

func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunParallel(ctx, host, inputs, limit)
}

func executionError(err error, trace []runtime.TraceEvent) error {
	message, context := err.Error(), ""
	for _, event := range trace {
		if event.Status != runtime.Error {
			continue
		}
		switch event.Node {
		case "count":
			message = "examples/state.lip:2:5: " + event.Reason
			context = "\n  2 |     count = state(0)\n    |     ^"
		case "doubled":
			message = "examples/state.lip:3:5: " + event.Reason
			context = "\n  3 |     doubled = count * 2\n    |     ^"
		case "__return_0":
			message = "examples/state.lip:4:5: " + event.Reason
			context = "\n  4 |     return doubled + input\n    |     ^"
		}
		break
	}
	if hint := runtime.ExecutionHint(err); hint != "" {
		context += "\n  hint: " + hint
	}
	return fmt.Errorf("%s%s", message, context)
}

func main() { os.Exit(runMain()) }

func runMain() int {
	inputs, err := parseCLIInputs(os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 2
	}
	_ = inputs
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	host := runtime.DefaultHost()
	value, trace, err := Run(ctx, host, inputs)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", executionError(err, trace))
		return 1
	}
	output, err := runtime.FormatValue(value)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	fmt.Println(output)
	return 0
}
