// Code generated by lipc; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"os"
	"strconv"

	"lipalpha/runtime"
)

func sampleInput(typ string, index int) runtime.Value {
	raw := os.Getenv("LIP_INPUT")
	if len(os.Args) > index+1 {
		raw = os.Args[index+1]
	}
	if raw == "" {
		if typ == "number" {
			return runtime.Value(float64(1))
		}
		if typ == "bool" {
			return runtime.Value(false)
		}
		return runtime.Value("World")
	}
	if n, err := strconv.ParseFloat(raw, 64); err == nil && typ != "string" {
		return runtime.Value(n)
	}
	if typ == "bool" && (raw == "true" || raw == "false") {
		return runtime.Value(raw == "true")
	}
	return runtime.Value(raw)
}

func buildGraph(host runtime.Host) *runtime.Graph {
	g := runtime.NewGraph()
	g.Add(runtime.NodeSpec{Name: "greeting", Op: "", Pure: true, Deps: []string{"request"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("+", runtime.Value("Hello, "), values["request"])
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}})
	g.Add(runtime.NodeSpec{Name: "__return_0", Op: "", Pure: true, Deps: []string{"greeting"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return runtime.Ready(values["greeting"])
	}, Output: true})
	return g
}

func checkInputs(inputs map[string]runtime.Value) error {
	if _, ok := inputs["request"]; !ok {
		return fmt.Errorf("missing flow input request")
	}
	if err := runtime.CheckType(inputs["request"], "string"); err != nil {
		return fmt.Errorf("input request: %w", err)
	}
	return nil
}

type Instance struct{ engine *runtime.Instance }

func NewInstance(host runtime.Host, inputs map[string]runtime.Value) (*Instance, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, err
	}
	graph := buildGraph(host)
	return &Instance{engine: graph.NewInstance(host, inputs)}, nil
}

func (i *Instance) Tick(ctx context.Context, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if i == nil || i.engine == nil {
		return nil, nil, fmt.Errorf("nil flow instance")
	}
	return i.engine.Tick(ctx, inputs)
}

func (i *Instance) SetState(name string, value runtime.Value) error {
	if i == nil || i.engine == nil {
		return fmt.Errorf("nil flow instance")
	}
	return i.engine.SetState(name, value)
}

func (i *Instance) State(name string) (runtime.Value, bool) {
	if i == nil || i.engine == nil {
		return nil, false
	}
	return i.engine.State(name)
}

func (i *Instance) TickCount() uint64 {
	if i == nil || i.engine == nil {
		return 0
	}
	return i.engine.TickCount()
}

func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunAuto(ctx, host, inputs)
}

func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).Run(ctx, inputs)
}

func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunParallel(ctx, host, inputs, limit)
}

func main() {
	ctx := context.Background()
	host := runtime.DefaultHost()
	inputs := map[string]runtime.Value{}
	inputs["request"] = sampleInput("string", 0)
	value, trace, err := Run(ctx, host, inputs)
	if err != nil {
		fmt.Println("error:", err)
		for _, event := range trace {
			fmt.Printf("%s %s %s\n", event.Node, event.Status, event.Reason)
		}
		os.Exit(1)
	}
	fmt.Println(value)
}
