// Code generated by lipc; DO NOT EDIT.
// LIP 0.6.3
package main

import (
	"context"
	"fmt"
	"os"

	"lipalpha/runtime"
)

type Dependency struct {
	Kind  string
	Spec  string
	Alias string
}

func RequiredDependencies() []Dependency {
	return []Dependency{{Kind: "host", Spec: "start"}, {Kind: "host", Spec: "revise"}, {Kind: "host", Spec: "verify"}}
}

func parseCLIInputs(args []string) (map[string]runtime.Value, error) {
	inputs, err := runtime.ParseCLIInputs(args, []runtime.Input{{Name: "input", Type: "string"}})
	if err != nil {
		return nil, fmt.Errorf("%w\nusage: %s <input:string>", err, os.Args[0])
	}
	return inputs, nil
}

func buildGraph(host runtime.Host) *runtime.Graph {
	host = host.Clone()
	g := runtime.NewGraphWithOptions(runtime.GraphOptions{ReleaseIntermediates: true})
	g.Add(runtime.NodeSpec{Name: "result", Effect: host.EffectsOf([]string{"start", "revise", "verify"}), Deps: []string{"input"}, Gates: nil, Feedback: &runtime.FeedbackSpec{Attempts: 3, Init: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "start", []runtime.Value{values["input"]})
	}, Step: func(ctx context.Context, current runtime.Value) runtime.Result {
		return host.Call(ctx, "revise", []runtime.Value{current})
	}, Verify: func(ctx context.Context, current runtime.Value) runtime.Result {
		return host.Call(ctx, "verify", []runtime.Value{current})
	}}})
	g.Add(runtime.NodeSpec{Name: "__return_0", Op: "", Effect: runtime.EffectPure, Deps: []string{"result"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return runtime.Ready(values["result"])
	}, Output: true, ValueType: "any"})
	return g
}

func checkInputUpdates(inputs map[string]runtime.Value) error {
	for name, value := range inputs {
		_ = value
		switch name {
		case "input":
			if err := runtime.CheckType(value, "string"); err != nil {
				return fmt.Errorf("input input: %w", err)
			}
		default:
			return fmt.Errorf("unknown flow input %q", name)
		}
	}
	return nil
}

func checkInputs(inputs map[string]runtime.Value) error {
	if _, ok := inputs["input"]; !ok {
		return fmt.Errorf("missing flow input input")
	}
	return checkInputUpdates(inputs)
}

func checkHost(host runtime.Host) error {
	if err := host.RequireOperation("start"); err != nil {
		return err
	}
	if err := host.RequireOperation("revise"); err != nil {
		return err
	}
	if err := host.RequireOperation("verify"); err != nil {
		return err
	}
	return nil
}

type Instance struct{ engine *runtime.Instance }

func NewInstance(host runtime.Host, inputs map[string]runtime.Value) (*Instance, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, err
	}
	graph := buildGraph(host)
	return &Instance{engine: graph.NewInstance(host, inputs)}, nil
}

func (i *Instance) Tick(ctx context.Context, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if i == nil || i.engine == nil {
		return nil, nil, fmt.Errorf("nil flow instance")
	}
	if err := checkInputUpdates(inputs); err != nil {
		return nil, nil, err
	}
	return i.engine.Tick(ctx, inputs)
}

func (i *Instance) SetState(name string, value runtime.Value) error {
	if i == nil || i.engine == nil {
		return fmt.Errorf("nil flow instance")
	}
	return i.engine.SetState(name, value)
}

func (i *Instance) State(name string) (runtime.Value, bool) {
	if i == nil || i.engine == nil {
		return nil, false
	}
	return i.engine.State(name)
}

func (i *Instance) TickCount() uint64 {
	if i == nil || i.engine == nil {
		return 0
	}
	return i.engine.TickCount()
}

func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunAuto(ctx, host, inputs)
}

func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).Run(ctx, inputs)
}

func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunParallel(ctx, host, inputs, limit)
}

func executionError(err error, trace []runtime.TraceEvent) error {
	message, context := err.Error(), ""
	for _, event := range trace {
		if event.Status != runtime.Error {
			continue
		}
		switch event.Node {
		case "result":
			message = "examples/feedback.lip:6:5: " + event.Reason
			context = "\n  6 |     result = feedback(start(input), revise, verify, 3)\n    |     ^"
		case "__return_0":
			message = "examples/feedback.lip:7:5: " + event.Reason
			context = "\n  7 |     return result\n    |     ^"
		}
		break
	}
	if line, column, found := runtime.SourcePosition(err); found {
		switch fmt.Sprintf("%d:%d", line, column) {
		}
	}
	if hint := runtime.ExecutionHint(err); hint != "" {
		context += "\n  hint: " + hint
	}
	return fmt.Errorf("%s%s", message, context)
}

func main() { os.Exit(runMain()) }

func runMain() int {
	inputs, err := parseCLIInputs(os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 2
	}
	_ = inputs
	fmt.Fprintln(os.Stderr, "host/go dependencies require a Go host program; use library mode")
	return 1
}
