// Code generated by lipc; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"math"
	"os"
	"strconv"

	"lipalpha/runtime"
)

type Dependency struct {
	Kind string
	Spec string
}

func RequiredDependencies() []Dependency { return []Dependency{} }

func parseCLIInputs(args []string) (map[string]runtime.Value, error) {
	if len(args) != 1 {
		return nil, fmt.Errorf("usage: %s <input:number>", os.Args[0])
	}
	inputs := map[string]runtime.Value{}
	raw0 := args[0]
	number0, err := strconv.ParseFloat(raw0, 64)
	if err != nil || math.IsNaN(number0) || math.IsInf(number0, 0) {
		return nil, fmt.Errorf("argument 1 (input): expected a finite number, got %q", raw0)
	}
	inputs["input"] = number0
	return inputs, nil
}

func buildGraph(host runtime.Host) *runtime.Graph {
	g := runtime.NewGraph()
	g.Add(runtime.NodeSpec{Name: "left", Op: "", Pure: true, Deps: []string{"input"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("+", values["input"], runtime.Value(1))
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}})
	g.Add(runtime.NodeSpec{Name: "right", Op: "", Pure: true, Deps: []string{"input"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("*", values["input"], runtime.Value(2))
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}})
	g.Add(runtime.NodeSpec{Name: "total", Op: "", Pure: true, Deps: []string{"left", "right"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("+", values["left"], values["right"])
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}})
	g.Add(runtime.NodeSpec{Name: "__return_0", Op: "", Pure: true, Deps: []string{"total"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return runtime.Ready(values["total"])
	}, Output: true})
	return g
}

func checkInputs(inputs map[string]runtime.Value) error {
	if _, ok := inputs["input"]; !ok {
		return fmt.Errorf("missing flow input input")
	}
	if err := runtime.CheckType(inputs["input"], "number"); err != nil {
		return fmt.Errorf("input input: %w", err)
	}
	return nil
}

type Instance struct{ engine *runtime.Instance }

func NewInstance(host runtime.Host, inputs map[string]runtime.Value) (*Instance, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, err
	}
	graph := buildGraph(host)
	return &Instance{engine: graph.NewInstance(host, inputs)}, nil
}

func (i *Instance) Tick(ctx context.Context, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if i == nil || i.engine == nil {
		return nil, nil, fmt.Errorf("nil flow instance")
	}
	return i.engine.Tick(ctx, inputs)
}

func (i *Instance) SetState(name string, value runtime.Value) error {
	if i == nil || i.engine == nil {
		return fmt.Errorf("nil flow instance")
	}
	return i.engine.SetState(name, value)
}

func (i *Instance) State(name string) (runtime.Value, bool) {
	if i == nil || i.engine == nil {
		return nil, false
	}
	return i.engine.State(name)
}

func (i *Instance) TickCount() uint64 {
	if i == nil || i.engine == nil {
		return 0
	}
	return i.engine.TickCount()
}

func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunAuto(ctx, host, inputs)
}

func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).Run(ctx, inputs)
}

func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunParallel(ctx, host, inputs, limit)
}

func main() {
	ctx := context.Background()
	host := runtime.DefaultHost()
	inputs := map[string]runtime.Value{}
	parsed, err := parseCLIInputs(os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}
	inputs = parsed
	value, trace, err := Run(ctx, host, inputs)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		for _, event := range trace {
			fmt.Fprintf(os.Stderr, "%s %s %s\n", event.Node, event.Status, event.Reason)
		}
		os.Exit(1)
	}
	fmt.Println(value)
}
