// Code generated by lipc; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"os"
	"strconv"

	"lipalpha/runtime"
)

func sampleInput(typ string) runtime.Value {
	raw := os.Getenv("LIP_INPUT")
	if raw == "" {
		if typ == "number" {
			return runtime.Value(float64(1))
		}
		if typ == "bool" {
			return runtime.Value(false)
		}
		return runtime.Value("World")
	}
	if n, err := strconv.ParseFloat(raw, 64); err == nil && typ != "string" {
		return runtime.Value(n)
	}
	if typ == "bool" && (raw == "true" || raw == "false") {
		return runtime.Value(raw == "true")
	}
	return runtime.Value(raw)
}

func buildGraph(host runtime.Host) *runtime.Graph {
	g := runtime.NewGraph()
	g.Add(runtime.NodeSpec{Name: "left", Op: "", Pure: true, Deps: []string{"input"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("+", values["input"], runtime.Value(1))
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}})
	g.Add(runtime.NodeSpec{Name: "right", Op: "", Pure: true, Deps: []string{"input"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("*", values["input"], runtime.Value(2))
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}})
	g.Add(runtime.NodeSpec{Name: "total", Op: "", Pure: true, Deps: []string{"left", "right"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0, err := runtime.Binary("+", values["left"], values["right"])
		if err != nil {
			return runtime.Failed(err)
		}
		return runtime.Ready(value0)
	}})
	g.Add(runtime.NodeSpec{Name: "__return_0", Op: "", Pure: true, Deps: []string{"total"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return runtime.Ready(values["total"])
	}, Output: true})
	return g
}

func checkInputs(inputs map[string]runtime.Value) error {
	if _, ok := inputs["input"]; !ok {
		return fmt.Errorf("missing flow input input")
	}
	if err := runtime.CheckType(inputs["input"], "number"); err != nil {
		return fmt.Errorf("input input: %w", err)
	}
	return nil
}

func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunAuto(ctx, host, inputs)
}

func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).Run(ctx, inputs)
}

func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunParallel(ctx, host, inputs, limit)
}

func main() {
	ctx := context.Background()
	host := runtime.DefaultHost()
	inputs := map[string]runtime.Value{}
	inputs["input"] = sampleInput("number")
	value, trace, err := Run(ctx, host, inputs)
	if err != nil {
		fmt.Println("error:", err)
		for _, event := range trace {
			fmt.Printf("%s %s %s\n", event.Node, event.Status, event.Reason)
		}
		return
	}
	fmt.Println(value)
}
