// Code generated by lipc; DO NOT EDIT.
package sessionflow

import (
	"context"
	"fmt"

	"lipalpha/runtime"
)

type Dependency struct {
	Kind  string
	Spec  string
	Alias string
}

func RequiredDependencies() []Dependency {
	return []Dependency{{Kind: "host", Spec: "fetch"}, {Kind: "host", Spec: "write_report"}}
}

func __lip_fn_start(host runtime.Host) runtime.Op {
	return func(ctx context.Context, args []runtime.Value) runtime.Result {
		ctx, err := runtime.EnterFunction(ctx)
		if err != nil {
			return runtime.Failed(err)
		}
		if len(args) != 1 {
			return runtime.Failed(fmt.Errorf("function start expects 1 arguments, got %d", len(args)))
		}
		if err := runtime.CheckType(args[0], "number"); err != nil {
			return runtime.Failed(fmt.Errorf("argument input: %w", err))
		}
		if err := runtime.CheckType(args[0], "number"); err != nil {
			return runtime.Failed(fmt.Errorf("function start result: %w", err))
		}
		return runtime.Ready(args[0])
	}
}

func __lip_fn_revise(host runtime.Host) runtime.Op {
	return func(ctx context.Context, args []runtime.Value) runtime.Result {
		ctx, err := runtime.EnterFunction(ctx)
		if err != nil {
			return runtime.Failed(err)
		}
		if len(args) != 1 {
			return runtime.Failed(fmt.Errorf("function revise expects 1 arguments, got %d", len(args)))
		}
		if err := runtime.CheckType(args[0], "number"); err != nil {
			return runtime.Failed(fmt.Errorf("argument candidate: %w", err))
		}
		value0, err := runtime.Binary("+", args[0], runtime.Value(float64(1)))
		if err != nil {
			return runtime.Failed(err)
		}
		if err := runtime.CheckType(value0, "number"); err != nil {
			return runtime.Failed(fmt.Errorf("function revise result: %w", err))
		}
		return runtime.Ready(value0)
	}
}

func __lip_fn_verify(host runtime.Host) runtime.Op {
	return func(ctx context.Context, args []runtime.Value) runtime.Result {
		ctx, err := runtime.EnterFunction(ctx)
		if err != nil {
			return runtime.Failed(err)
		}
		if len(args) != 1 {
			return runtime.Failed(fmt.Errorf("function verify expects 1 arguments, got %d", len(args)))
		}
		if err := runtime.CheckType(args[0], "number"); err != nil {
			return runtime.Failed(fmt.Errorf("argument candidate: %w", err))
		}
		value0, err := runtime.Binary(">=", args[0], runtime.Value(float64(3)))
		if err != nil {
			return runtime.Failed(err)
		}
		if err := runtime.CheckType(value0, "bool"); err != nil {
			return runtime.Failed(fmt.Errorf("function verify result: %w", err))
		}
		return runtime.Ready(value0)
	}
}

func buildGraph(host runtime.Host) *runtime.Graph {
	host = host.Clone()
	g := runtime.NewGraph()
	host.RegisterPure("start", __lip_fn_start(host))
	host.RegisterPure("revise", __lip_fn_revise(host))
	host.RegisterPure("verify", __lip_fn_verify(host))
	g.Add(runtime.NodeSpec{Name: "count", Effect: runtime.EffectPure, State: true, ValueType: "number", Deps: nil, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return runtime.Ready(runtime.Value(float64(0)))
	}})
	g.Add(runtime.NodeSpec{Name: "fetched", Op: "fetch", Deps: []string{"input"}, Gates: []string{"enabled"}, Retry: &runtime.RetrySpec{Attempts: 3, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "fetch", []runtime.Value{values["input"]})
	}}, Gate: func(values map[string]runtime.Value) (bool, error) {
		ok, err := runtime.Bool(values["enabled"])
		if err != nil {
			return false, err
		}
		if !ok {
			return false, nil
		}
		return true, nil
	}})
	g.Add(runtime.NodeSpec{Name: "candidate", Deps: []string{"fetched"}, Gates: []string{"enabled"}, Feedback: &runtime.FeedbackSpec{Attempts: 3, Init: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "start", []runtime.Value{values["fetched"]})
	}, Step: func(ctx context.Context, current runtime.Value) runtime.Result {
		return host.Call(ctx, "revise", []runtime.Value{current})
	}, Verify: func(ctx context.Context, current runtime.Value) runtime.Result {
		return host.Call(ctx, "verify", []runtime.Value{current})
	}}, Gate: func(values map[string]runtime.Value) (bool, error) {
		ok, err := runtime.Bool(values["enabled"])
		if err != nil {
			return false, err
		}
		if !ok {
			return false, nil
		}
		return true, nil
	}})
	g.Add(runtime.NodeSpec{Name: "report", Op: "", Effect: runtime.EffectPure, Deps: []string{"count", "candidate"}, Gates: []string{"enabled"}, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		value0 := map[string]runtime.Value{}
		value0["count"] = values["count"]
		value0["result"] = values["candidate"]
		return runtime.Ready(value0)
	}, Gate: func(values map[string]runtime.Value) (bool, error) {
		ok, err := runtime.Bool(values["enabled"])
		if err != nil {
			return false, err
		}
		if !ok {
			return false, nil
		}
		return true, nil
	}})
	g.Add(runtime.NodeSpec{Name: "__expr_0", Op: "write_report", Effect: runtime.EffectUnknown, Deps: []string{"report"}, Gates: []string{"enabled"}, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "write_report", []runtime.Value{values["report"]})
	}, Gate: func(values map[string]runtime.Value) (bool, error) {
		ok, err := runtime.Bool(values["enabled"])
		if err != nil {
			return false, err
		}
		if !ok {
			return false, nil
		}
		return true, nil
	}})
	g.Add(runtime.NodeSpec{Name: "__return_0", Op: "", Effect: runtime.EffectPure, Deps: []string{"report"}, Gates: []string{"enabled"}, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return runtime.Ready(values["report"])
	}, Gate: func(values map[string]runtime.Value) (bool, error) {
		ok, err := runtime.Bool(values["enabled"])
		if err != nil {
			return false, err
		}
		if !ok {
			return false, nil
		}
		return true, nil
	}, Output: true, ValueType: "object?"})
	return g
}

func checkInputUpdates(inputs map[string]runtime.Value) error {
	for name, value := range inputs {
		_ = value
		switch name {
		case "input":
			if err := runtime.CheckType(value, "number"); err != nil {
				return fmt.Errorf("input input: %w", err)
			}
		case "enabled":
			if err := runtime.CheckType(value, "bool"); err != nil {
				return fmt.Errorf("input enabled: %w", err)
			}
		default:
			return fmt.Errorf("unknown flow input %q", name)
		}
	}
	return nil
}

func checkInputs(inputs map[string]runtime.Value) error {
	if _, ok := inputs["input"]; !ok {
		return fmt.Errorf("missing flow input input")
	}
	if _, ok := inputs["enabled"]; !ok {
		return fmt.Errorf("missing flow input enabled")
	}
	return checkInputUpdates(inputs)
}

func checkHost(host runtime.Host) error {
	if err := host.RequireOperation("fetch"); err != nil {
		return err
	}
	if err := host.RequireOperation("write_report"); err != nil {
		return err
	}
	return nil
}

type Instance struct{ engine *runtime.Instance }

func NewInstance(host runtime.Host, inputs map[string]runtime.Value) (*Instance, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, err
	}
	graph := buildGraph(host)
	return &Instance{engine: graph.NewInstance(host, inputs)}, nil
}

func (i *Instance) Tick(ctx context.Context, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if i == nil || i.engine == nil {
		return nil, nil, fmt.Errorf("nil flow instance")
	}
	if err := checkInputUpdates(inputs); err != nil {
		return nil, nil, err
	}
	return i.engine.Tick(ctx, inputs)
}

func (i *Instance) SetState(name string, value runtime.Value) error {
	if i == nil || i.engine == nil {
		return fmt.Errorf("nil flow instance")
	}
	return i.engine.SetState(name, value)
}

func (i *Instance) State(name string) (runtime.Value, bool) {
	if i == nil || i.engine == nil {
		return nil, false
	}
	return i.engine.State(name)
}

func (i *Instance) TickCount() uint64 {
	if i == nil || i.engine == nil {
		return 0
	}
	return i.engine.TickCount()
}

func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunAuto(ctx, host, inputs)
}

func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).Run(ctx, inputs)
}

func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunParallel(ctx, host, inputs, limit)
}
