package compiler

import (
	"fmt"
	gotoken "go/token"
	"strconv"
	"strings"

	"lipalpha/compiler/ast"
)

type GenerateOptions struct {
	PackageName string
	IncludeMain bool
}

func GenerateGo(g *Graph) (string, error) {
	return GenerateGoWithOptions(g, GenerateOptions{PackageName: "main", IncludeMain: true})
}

func GenerateGoWithOptions(g *Graph, options GenerateOptions) (string, error) {
	if g == nil {
		return "", fmt.Errorf("cannot generate a nil graph")
	}
	if options.PackageName == "" {
		options.PackageName = "main"
	}
	if !gotoken.IsIdentifier(options.PackageName) || options.PackageName == "_" {
		return "", fmt.Errorf("invalid Go package name %q", options.PackageName)
	}
	if options.IncludeMain && options.PackageName != "main" {
		return "", fmt.Errorf("standalone generation requires package main; use library mode (-no-main) for package %s", options.PackageName)
	}
	var b strings.Builder
	b.WriteString("// Code generated by lipc; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s\n\n", options.PackageName)
	b.WriteString("import (\n\t\"context\"\n")
	// Generated input checks, strict CLI parsing, instances and optional mains use fmt.
	b.WriteString("\t\"fmt\"\n")
	if options.IncludeMain {
		b.WriteString("\t\"os\"\n")
	}
	b.WriteString("\n\t\"lipalpha/runtime\"\n)\n\n")
	b.WriteString("type Dependency struct { Kind string; Spec string }\n\nfunc RequiredDependencies() []Dependency { return []Dependency{")
	for _, dependency := range g.Dependencies {
		fmt.Fprintf(&b, "{Kind: %s, Spec: %s},", quote(dependency.Kind), quote(dependency.Spec))
	}
	b.WriteString("} }\n\n")
	if options.IncludeMain {
		b.WriteString("func parseCLIInputs(args []string) (map[string]runtime.Value, error) {\n")
		b.WriteString("\tinputs, err := runtime.ParseCLIInputs(args, []runtime.Input{")
		for _, param := range g.Params {
			fmt.Fprintf(&b, "{Name: %s, Type: %s},", quote(param), quote(gParamType(g, param)))
		}
		b.WriteString("})\n")
		b.WriteString("\tif err != nil { return nil, fmt.Errorf(\"%w\\nusage: %s")
		for _, param := range g.Params {
			fmt.Fprintf(&b, " <%s:%s>", param, gParamType(g, param))
		}
		b.WriteString("\", err, os.Args[0]) }; return inputs, nil\n}\n\n")
	}
	for _, fn := range g.Functions {
		code, err := emitFunction(fn)
		if err != nil {
			return "", err
		}
		b.WriteString(code)
		b.WriteString("\n")
	}
	b.WriteString("func buildGraph(host runtime.Host) *runtime.Graph {\n\thost = host.Clone()\n\tg := runtime.NewGraph()\n")
	for _, fn := range g.Functions {
		fmt.Fprintf(&b, "\thost.RegisterPure(%s, __lip_fn_%s(host))\n", quote(fn.Name), fn.Name)
	}
	for _, n := range g.Nodes {
		if n.FeedbackAttempts > 0 {
			call, ok := n.Expr.(*ast.CallExpr)
			if !ok || len(call.Args) != 4 {
				return "", fmt.Errorf("node %s: invalid feedback expression", n.Name)
			}
			initial, ok := call.Args[0].(*ast.CallExpr)
			if !ok {
				return "", fmt.Errorf("node %s: feedback initial expression must be a call", n.Name)
			}
			fmt.Fprintf(&b, "\tg.Add(runtime.NodeSpec{Name: %s, Pure: false, Deps: %s, Gates: %s, Feedback: &runtime.FeedbackSpec{Attempts: %d, Init: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {\n", quote(n.Name), stringSlice(n.Deps), stringSlice(n.Gates), n.FeedbackAttempts)
			expr, err := emitExpr(initial)
			if err != nil {
				return "", fmt.Errorf("node %s: %w", n.Name, err)
			}
			b.WriteString(expr)
			fmt.Fprintf(&b, "\n\t}, Step: func(ctx context.Context, current runtime.Value) runtime.Result { return host.Call(ctx, %s, []runtime.Value{current}) }, Verify: func(ctx context.Context, current runtime.Value) runtime.Result { return host.Call(ctx, %s, []runtime.Value{current}) }},", quote(n.FeedbackStep), quote(n.FeedbackVerify))
			if len(n.Gates) > 0 {
				b.WriteString(" Gate: func(values map[string]runtime.Value) (bool, error) {\n")
				for _, gate := range n.Gates {
					fmt.Fprintf(&b, "\t\tok, err := runtime.Bool(values[%s]); if err != nil { return false, err }; if !ok { return false, nil }\n", quote(gate))
				}
				b.WriteString("\t\treturn true, nil\n\t},")
			}
			if n.Output {
				fmt.Fprintf(&b, " Output: true, ValueType: %s,", quote(strings.TrimSuffix(g.ReturnType, "?")))
			}
			b.WriteString("})\n")
			continue
		}
		if n.RetryAttempts > 0 {
			call, ok := n.Expr.(*ast.CallExpr)
			if !ok || len(call.Args) != 2 {
				return "", fmt.Errorf("node %s: invalid retry expression", n.Name)
			}
			inner, ok := call.Args[0].(*ast.CallExpr)
			if !ok {
				return "", fmt.Errorf("node %s: retry first argument must be a call", n.Name)
			}
			fmt.Fprintf(&b, "\tg.Add(runtime.NodeSpec{Name: %s, Op: %s, Pure: false, Deps: %s, Gates: %s, Retry: &runtime.RetrySpec{Attempts: %d, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {\n", quote(n.Name), quote(inner.Name), stringSlice(n.Deps), stringSlice(n.Gates), n.RetryAttempts)
			expr, err := emitExpr(inner)
			if err != nil {
				return "", fmt.Errorf("node %s: %w", n.Name, err)
			}
			b.WriteString(expr)
			b.WriteString("\n\t}},")
			if len(n.Gates) > 0 {
				b.WriteString(" Gate: func(values map[string]runtime.Value) (bool, error) {\n")
				for _, gate := range n.Gates {
					fmt.Fprintf(&b, "\t\tok, err := runtime.Bool(values[%s]); if err != nil { return false, err }; if !ok { return false, nil }\n", quote(gate))
				}
				b.WriteString("\t\treturn true, nil\n\t},")
			}
			if n.Output {
				fmt.Fprintf(&b, " Output: true, ValueType: %s,", quote(strings.TrimSuffix(g.ReturnType, "?")))
			}
			b.WriteString("})\n")
			continue
		}
		if n.State {
			call, ok := n.Expr.(*ast.CallExpr)
			if !ok || len(call.Args) != 1 {
				return "", fmt.Errorf("node %s: invalid state expression", n.Name)
			}
			fmt.Fprintf(&b, "\tg.Add(runtime.NodeSpec{Name: %s, Pure: true, State: true, ValueType: %s, Deps: %s, Gates: %s, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {\n", quote(n.Name), quote(runtimeType(n.Type)), stringSlice(n.Deps), stringSlice(n.Gates))
			expr, err := emitExpr(call.Args[0])
			if err != nil {
				return "", fmt.Errorf("node %s: %w", n.Name, err)
			}
			b.WriteString(expr)
			b.WriteString("\n\t},")
			if len(n.Gates) > 0 {
				b.WriteString(" Gate: func(values map[string]runtime.Value) (bool, error) {\n")
				for _, gate := range n.Gates {
					fmt.Fprintf(&b, "\t\tok, err := runtime.Bool(values[%s]); if err != nil { return false, err }; if !ok { return false, nil }\n", quote(gate))
				}
				b.WriteString("\t\treturn true, nil\n\t},")
			}
			if n.Output {
				fmt.Fprintf(&b, " Output: true, ValueType: %s,", quote(strings.TrimSuffix(g.ReturnType, "?")))
			}
			b.WriteString("})\n")
			continue
		}
		if comp, ok := n.Expr.(*ast.ComprehensionExpr); ok {
			source, sourceOK := comp.Source.(*ast.IdentExpr)
			if !sourceOK {
				return "", fmt.Errorf("node %s: comprehension source must be an identifier", n.Name)
			}
			ops := callNames(comp.Element)
			pure := pureExpression(comp.Element, g.Functions)
			fmt.Fprintf(&b, "\tg.Add(runtime.NodeSpec{Name: %s, Pure: %t, Deps: %s, Gates: %s, Map: &runtime.MapSpec{Source: %s, Pure: %t, Ops: %s, Eval: func(ctx context.Context, item runtime.Value, values map[string]runtime.Value) runtime.Result {\n", quote(n.Name), pure, stringSlice(n.Deps), stringSlice(n.Gates), quote(source.Name), pure, stringSlice(ops))
			expr, err := emitMapElement(comp)
			if err != nil {
				return "", fmt.Errorf("node %s: %w", n.Name, err)
			}
			b.WriteString(expr)
			b.WriteString("\n\t}},")
			if len(n.Gates) > 0 {
				b.WriteString(" Gate: func(values map[string]runtime.Value) (bool, error) {\n")
				for _, gate := range n.Gates {
					fmt.Fprintf(&b, "\t\tok, err := runtime.Bool(values[%s]); if err != nil { return false, err }; if !ok { return false, nil }\n", quote(gate))
				}
				b.WriteString("\t\treturn true, nil\n\t},")
			}
			if n.Output {
				fmt.Fprintf(&b, " Output: true, ValueType: %s,", quote(strings.TrimSuffix(g.ReturnType, "?")))
			}
			b.WriteString("})\n")
			continue
		}
		callName := ""
		pure := pureExpression(n.Expr, g.Functions)
		if call, ok := n.Expr.(*ast.CallExpr); ok {
			callName = call.Name
		}
		fmt.Fprintf(&b, "\tg.Add(runtime.NodeSpec{Name: %s, Op: %s, Pure: %t, Deps: %s, Gates: %s, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {\n", quote(n.Name), quote(callName), pure, stringSlice(n.Deps), stringSlice(n.Gates))
		expr, err := emitExpr(n.Expr)
		if err != nil {
			return "", fmt.Errorf("node %s: %w", n.Name, err)
		}
		b.WriteString(expr)
		b.WriteString("\n\t},")
		if len(n.Gates) > 0 {
			b.WriteString(" Gate: func(values map[string]runtime.Value) (bool, error) {\n")
			for _, gate := range n.Gates {
				fmt.Fprintf(&b, "\t\tok, err := runtime.Bool(values[%s]); if err != nil { return false, err }; if !ok { return false, nil }\n", quote(gate))
			}
			b.WriteString("\t\treturn true, nil\n\t},")
		}
		if n.Output {
			fmt.Fprintf(&b, " Output: true, ValueType: %s,", quote(strings.TrimSuffix(g.ReturnType, "?")))
		}
		b.WriteString("})\n")
	}
	b.WriteString("\treturn g\n}\n\n")
	b.WriteString("func checkInputUpdates(inputs map[string]runtime.Value) error {\n\tfor name, value := range inputs {\n\t\t_ = value\n\t\tswitch name {\n")
	for _, param := range g.Params {
		fmt.Fprintf(&b, "\t\tcase %s: if err := runtime.CheckType(value, %s); err != nil { return fmt.Errorf(\"input %s: %%w\", err) }\n", quote(param), quote(gParamType(g, param)), param)
	}
	b.WriteString("\t\tdefault: return fmt.Errorf(\"unknown flow input %q\", name)\n\t\t}\n\t}\n\treturn nil\n}\n\n")
	b.WriteString("func checkInputs(inputs map[string]runtime.Value) error {\n")
	for _, param := range g.Params {
		fmt.Fprintf(&b, "\tif _, ok := inputs[%s]; !ok { return fmt.Errorf(\"missing flow input %s\") }\n", quote(param), param)
	}
	b.WriteString("\treturn checkInputUpdates(inputs)\n}\n\n")
	b.WriteString("func checkHost(host runtime.Host) error {\n")
	for _, operation := range requiredHostOperations(g) {
		fmt.Fprintf(&b, "\tif err := host.RequireOperation(%s); err != nil { return err }\n", quote(operation))
	}
	b.WriteString("\treturn nil\n}\n\n")
	b.WriteString("type Instance struct { engine *runtime.Instance }\n\n")
	b.WriteString("func NewInstance(host runtime.Host, inputs map[string]runtime.Value) (*Instance, error) { if err := checkInputs(inputs); err != nil { return nil, err }; if err := checkHost(host); err != nil { return nil, err }; graph := buildGraph(host); return &Instance{engine: graph.NewInstance(host, inputs)}, nil }\n\n")
	b.WriteString("func (i *Instance) Tick(ctx context.Context, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) { if i == nil || i.engine == nil { return nil, nil, fmt.Errorf(\"nil flow instance\") }; if err := checkInputUpdates(inputs); err != nil { return nil, nil, err }; return i.engine.Tick(ctx, inputs) }\n\n")
	b.WriteString("func (i *Instance) SetState(name string, value runtime.Value) error { if i == nil || i.engine == nil { return fmt.Errorf(\"nil flow instance\") }; return i.engine.SetState(name, value) }\n\n")
	b.WriteString("func (i *Instance) State(name string) (runtime.Value, bool) { if i == nil || i.engine == nil { return nil, false }; return i.engine.State(name) }\n\n")
	b.WriteString("func (i *Instance) TickCount() uint64 { if i == nil || i.engine == nil { return 0 }; return i.engine.TickCount() }\n\n")
	b.WriteString("func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) { if err := checkInputs(inputs); err != nil { return nil, nil, err }; if err := checkHost(host); err != nil { return nil, nil, err }; return buildGraph(host).RunAuto(ctx, host, inputs) }\n\n")
	b.WriteString("func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) { if err := checkInputs(inputs); err != nil { return nil, nil, err }; if err := checkHost(host); err != nil { return nil, nil, err }; return buildGraph(host).Run(ctx, inputs) }\n\n")
	b.WriteString("func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) { if err := checkInputs(inputs); err != nil { return nil, nil, err }; if err := checkHost(host); err != nil { return nil, nil, err }; return buildGraph(host).RunParallel(ctx, host, inputs, limit) }\n")
	if options.IncludeMain {
		b.WriteString("\nfunc main() {\n\tctx := context.Background()\n\thost := runtime.DefaultHost()\n\tinputs := map[string]runtime.Value{}\n")
		b.WriteString("\tparsed, err := parseCLIInputs(os.Args[1:])\n\tif err != nil { fmt.Fprintln(os.Stderr, err); os.Exit(2) }\n\tinputs = parsed\n")
		if hasHostOrGoDependency(g) {
			b.WriteString("\tfmt.Fprintln(os.Stderr, \"host/go dependencies require a Go host program; use library mode\")\n\t\tos.Exit(1)\n")
		}
		if hasPythonDependency(g) {
			// A standalone program opts into the Python process only through an
			// explicit require python declaration. Library mode leaves ownership
			// to its Go host so it can choose the interpreter and policy.
			b.WriteString("\tworker, err := runtime.NewProcessHost(ctx, runtime.ProcessHostConfig{})\n\tif err != nil { fmt.Fprintln(os.Stderr, \"python worker:\", err); os.Exit(1) }\n\tdefer worker.Close()\n\thost = runtime.NewPythonHost(worker)\n")
		}
		b.WriteString("\tvalue, trace, err := Run(ctx, host, inputs)\n")
		b.WriteString("\tif err != nil { fmt.Fprintln(os.Stderr, \"error:\", err); for _, event := range trace { fmt.Fprintf(os.Stderr, \"%s %s %s\\n\", event.Node, event.Status, event.Reason) }; os.Exit(1) }\n")
		b.WriteString("\toutput, err := runtime.FormatValue(value); if err != nil { fmt.Fprintln(os.Stderr, err); os.Exit(1) }; fmt.Println(output)\n}\n")
	}
	return b.String(), nil
}

func hasPythonDependency(g *Graph) bool {
	for _, dependency := range g.Dependencies {
		if dependency.Kind == "python" {
			return true
		}
	}
	return false
}

func hasHostOrGoDependency(g *Graph) bool {
	for _, dependency := range g.Dependencies {
		if dependency.Kind == "host" || dependency.Kind == "go" {
			return true
		}
	}
	return false
}

func emitExpr(expr ast.Expr) (string, error) {
	ident := func(name string) string { return fmt.Sprintf("values[%s]", quote(name)) }
	emitter := newValueEmitter(ident, "\t\t")
	return emitResultExpr(expr, emitter)
}

func emitMapElement(comp *ast.ComprehensionExpr) (string, error) {
	ident := func(name string) string {
		if name == comp.Variable {
			return "item"
		}
		return fmt.Sprintf("values[%s]", quote(name))
	}
	emitter := newValueEmitter(ident, "\t\t\t")
	return emitResultExpr(comp.Element, emitter)
}

func emitResultExpr(expr ast.Expr, emitter *valueEmitter) (string, error) {
	if call, ok := expr.(*ast.CallExpr); ok && call.Name != "str" {
		args := make([]string, len(call.Args))
		for i, arg := range call.Args {
			value, err := emitter.value(arg)
			if err != nil {
				return "", err
			}
			args[i] = value
		}
		emitter.line("return host.Call(ctx, %s, []runtime.Value{%s})", quote(call.Name), strings.Join(args, ", "))
		return emitter.code(), nil
	}
	value, err := emitter.value(expr)
	if err != nil {
		return "", err
	}
	emitter.line("return runtime.Ready(%s)", value)
	return emitter.code(), nil
}

type valueEmitter struct {
	lines  *[]string
	next   *int
	indent string
	ident  func(string) string
}

func newValueEmitter(ident func(string) string, indent string) *valueEmitter {
	lines := []string{}
	next := 0
	return &valueEmitter{lines: &lines, next: &next, indent: indent, ident: ident}
}

func (e *valueEmitter) child(indent string) *valueEmitter {
	return &valueEmitter{lines: e.lines, next: e.next, indent: indent, ident: e.ident}
}

func (e *valueEmitter) line(format string, args ...any) {
	*e.lines = append(*e.lines, e.indent+fmt.Sprintf(format, args...))
}

func (e *valueEmitter) temp() string {
	name := fmt.Sprintf("value%d", *e.next)
	*e.next = *e.next + 1
	return name
}

func (e *valueEmitter) code() string { return strings.Join(*e.lines, "\n") }

func (e *valueEmitter) value(expr ast.Expr) (string, error) {
	switch x := expr.(type) {
	case *ast.LiteralExpr:
		return literal(x.Value), nil
	case *ast.IdentExpr:
		return e.ident(x.Name), nil
	case *ast.CallExpr:
		args := make([]string, len(x.Args))
		for i, arg := range x.Args {
			value, err := e.value(arg)
			if err != nil {
				return "", err
			}
			args[i] = value
		}
		if x.Name == "str" {
			if len(args) != 1 {
				return "", fmt.Errorf("str expects 1 argument")
			}
			return "runtime.StringValue(" + args[0] + ")", nil
		}
		value := e.temp()
		e.line("%s, err := runtime.ResolveValue(ctx, host.Call(ctx, %s, []runtime.Value{%s}))", value, quote(x.Name), strings.Join(args, ", "))
		e.line("if err != nil { return runtime.Failed(err) }")
		return value, nil
	case *ast.BinaryExpr:
		left, err := e.value(x.Left)
		if err != nil {
			return "", err
		}
		if x.Op == "&&" || x.Op == "||" {
			value, condition := e.temp(), e.temp()
			e.line("var %s runtime.Value", value)
			e.line("%s, err := runtime.Bool(%s)", condition, left)
			e.line("if err != nil { return runtime.Failed(err) }")
			e.line("%s = %s", value, condition)
			guard := condition
			if x.Op == "||" {
				guard = "!" + condition
			}
			e.line("if %s {", guard)
			branch := e.child(e.indent + "\t")
			right, err := branch.value(x.Right)
			if err != nil {
				return "", err
			}
			boolean := e.temp()
			branch.line("%s, err := runtime.Bool(%s)", boolean, right)
			branch.line("if err != nil { return runtime.Failed(err) }")
			branch.line("%s = %s", value, boolean)
			e.line("}")
			return value, nil
		}
		right, err := e.value(x.Right)
		if err != nil {
			return "", err
		}
		value := e.temp()
		e.line("%s, err := runtime.Binary(%s, %s, %s)", value, quote(x.Op), left, right)
		e.line("if err != nil { return runtime.Failed(err) }")
		return value, nil
	case *ast.ListExpr:
		items := make([]string, len(x.Items))
		for i, item := range x.Items {
			value, err := e.value(item)
			if err != nil {
				return "", err
			}
			items[i] = value
		}
		return "[]runtime.Value{" + strings.Join(items, ", ") + "}", nil
	case *ast.FieldExpr:
		object, err := e.value(x.Object)
		if err != nil {
			return "", err
		}
		value := e.temp()
		e.line("%s, err := runtime.Field(%s, %s)", value, object, quote(x.Name))
		e.line("if err != nil { return runtime.Failed(err) }")
		return value, nil
	case *ast.IndexExpr:
		object, err := e.value(x.Object)
		if err != nil {
			return "", err
		}
		index, err := e.value(x.Index)
		if err != nil {
			return "", err
		}
		value := e.temp()
		e.line("%s, err := runtime.Index(%s, %s)", value, object, index)
		e.line("if err != nil { return runtime.Failed(err) }")
		return value, nil
	case *ast.IfExpr:
		cond, err := e.value(x.Cond)
		if err != nil {
			return "", err
		}
		value := e.temp()
		e.line("var %s runtime.Value", value)
		condition := e.temp()
		e.line("%s, err := runtime.Bool(%s)", condition, cond)
		e.line("if err != nil { return runtime.Failed(err) }")
		e.line("if %s {", condition)
		thenEmitter := e.child(e.indent + "\t")
		thenValue, err := thenEmitter.value(x.Then)
		if err != nil {
			return "", err
		}
		thenEmitter.line("%s = %s", value, thenValue)
		e.line("} else {")
		elseEmitter := e.child(e.indent + "\t")
		elseValue, err := elseEmitter.value(x.Else)
		if err != nil {
			return "", err
		}
		elseEmitter.line("%s = %s", value, elseValue)
		e.line("}")
		return value, nil
	default:
		return "", fmt.Errorf("unsupported expression %T", expr)
	}
}

func emitFunction(fn *ast.Function) (string, error) {
	params := make(map[string]int, len(fn.Params))
	for i, param := range fn.Params {
		params[param] = i
	}
	ident := func(name string) string { return fmt.Sprintf("args[%d]", params[name]) }
	var b strings.Builder
	fmt.Fprintf(&b, "func __lip_fn_%s(host runtime.Host) runtime.Op {\n", fn.Name)
	b.WriteString("\treturn func(ctx context.Context, args []runtime.Value) runtime.Result {\n")
	fmt.Fprintf(&b, "\t\tif len(args) != %d { return runtime.Failed(fmt.Errorf(\"function %s expects %d arguments, got %%d\", len(args))) }\n", len(fn.Params), fn.Name, len(fn.Params))
	for i, param := range fn.Params {
		if typ := gFunctionParamType(fn, param); typ != "any" {
			fmt.Fprintf(&b, "\t\tif err := runtime.CheckType(args[%d], %s); err != nil { return runtime.Failed(fmt.Errorf(\"argument %s: %%w\", err)) }\n", i, quote(typ), param)
		}
	}
	emitter := newValueEmitter(ident, "\t\t")
	value, err := emitter.value(fn.Return)
	if err != nil {
		return "", fmt.Errorf("function %s: %w", fn.Name, err)
	}
	if code := emitter.code(); code != "" {
		b.WriteString(code)
		b.WriteString("\n")
	}
	resultType := fn.ReturnType
	if resultType == "" {
		resultType = fn.InferredReturnType
	}
	fmt.Fprintf(&b, "\t\tif err := runtime.CheckType(%s, %s); err != nil { return runtime.Failed(fmt.Errorf(\"function %s result: %%w\", err)) }\n", value, quote(runtimeType(resultType)), fn.Name)
	fmt.Fprintf(&b, "\t\treturn runtime.Ready(%s)\n", value)
	b.WriteString("\t}\n}\n")
	return b.String(), nil
}

func callNames(expr ast.Expr) []string {
	seen := map[string]bool{}
	var names []string
	var visit func(ast.Expr)
	visit = func(e ast.Expr) {
		switch x := e.(type) {
		case *ast.CallExpr:
			if !seen[x.Name] {
				seen[x.Name] = true
				names = append(names, x.Name)
			}
			for _, arg := range x.Args {
				visit(arg)
			}
		case *ast.BinaryExpr:
			visit(x.Left)
			visit(x.Right)
		case *ast.IfExpr:
			visit(x.Cond)
			visit(x.Then)
			visit(x.Else)
		case *ast.ListExpr:
			for _, item := range x.Items {
				visit(item)
			}
		case *ast.ComprehensionExpr:
			visit(x.Element)
			visit(x.Source)
		case *ast.FieldExpr:
			visit(x.Object)
		case *ast.IndexExpr:
			visit(x.Object)
			visit(x.Index)
		}
	}
	visit(expr)
	return names
}

func literal(v any) string {
	switch x := v.(type) {
	case string:
		return "runtime.Value(" + quote(x) + ")"
	case bool:
		if x {
			return "runtime.Value(true)"
		}
		return "runtime.Value(false)"
	case float64:
		return fmt.Sprintf("runtime.Value(float64(%s))", strconv.FormatFloat(x, 'g', -1, 64))
	default:
		return "runtime.Value(nil)"
	}
}

func stringSlice(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = quote(v)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func quote(s string) string { return strconv.Quote(s) }

func gParamType(g *Graph, name string) string {
	if g.ParamTypes != nil {
		if typ := g.ParamTypes[name]; typ != "" {
			return typ
		}
	}
	return "any"
}

func gFunctionParamType(fn *ast.Function, name string) string {
	if fn.ParamTypes != nil {
		if typ := fn.ParamTypes[name]; typ != "" {
			return typ
		}
	}
	return "any"
}

func runtimeType(typ string) string {
	if validTypeName(typ) {
		return typ
	}
	return "any"
}
func pureExpression(expr ast.Expr, functions []*ast.Function) bool {
	for _, called := range callNames(expr) {
		if called == "str" {
			continue
		}
		found := false
		for _, fn := range functions {
			if fn.Name == called {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	return true
}

func requiredHostOperations(g *Graph) []string {
	var operations []string
	for _, dependency := range g.Dependencies {
		if dependency.Kind != "host" {
			continue
		}
		operations = append(operations, dependency.Spec)
		if !strings.HasSuffix(dependency.Spec, ".*") {
			continue
		}
		prefix := strings.TrimSuffix(dependency.Spec, "*")
		for _, node := range g.Nodes {
			called := callNames(node.Expr)
			if node.FeedbackAttempts > 0 {
				called = append(called, node.FeedbackStep, node.FeedbackVerify)
			}
			for _, operation := range called {
				if strings.HasPrefix(operation, prefix) {
					operations = append(operations, operation)
				}
			}
		}
	}
	return unique(operations)
}
