package compiler

import (
	"fmt"
	"strconv"
	"strings"

	"lipalpha/compiler/ast"
)

type GenerateOptions struct {
	PackageName string
	IncludeMain bool
}

func GenerateGo(g *Graph) (string, error) {
	return GenerateGoWithOptions(g, GenerateOptions{PackageName: "main", IncludeMain: true})
}

func GenerateGoWithOptions(g *Graph, options GenerateOptions) (string, error) {
	if options.PackageName == "" {
		options.PackageName = "main"
	}
	var b strings.Builder
	b.WriteString("// Code generated by lipc; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s\n\n", options.PackageName)
	b.WriteString("import (\n\t\"context\"\n")
	// Generated input checks, instances and optional mains use fmt.
	b.WriteString("\t\"fmt\"\n")
	if options.IncludeMain {
		b.WriteString("\t\"os\"\n\t\"strconv\"\n")
	}
	b.WriteString("\n\t\"lipalpha/runtime\"\n)\n\n")
	if options.IncludeMain {
		b.WriteString("func sampleInput(typ string, index int) runtime.Value { raw := os.Getenv(\"LIP_INPUT\"); if len(os.Args) > index+1 { raw = os.Args[index+1] }; if raw == \"\" { if typ == \"number\" { return runtime.Value(float64(1)) }; if typ == \"bool\" { return runtime.Value(false) }; return runtime.Value(\"World\") }; if n, err := strconv.ParseFloat(raw, 64); err == nil && typ != \"string\" { return runtime.Value(n) }; if typ == \"bool\" && (raw == \"true\" || raw == \"false\") { return runtime.Value(raw == \"true\") }; return runtime.Value(raw) }\n\n")
	}
	for _, fn := range g.Functions {
		code, err := emitFunction(fn)
		if err != nil {
			return "", err
		}
		b.WriteString(code)
		b.WriteString("\n")
	}
	b.WriteString("func buildGraph(host runtime.Host) *runtime.Graph {\n\tg := runtime.NewGraph()\n")
	for _, fn := range g.Functions {
		if functionIsPure(fn) {
			fmt.Fprintf(&b, "\thost.RegisterPure(%s, __lip_fn_%s(host))\n", quote(fn.Name), fn.Name)
		} else {
			fmt.Fprintf(&b, "\thost.Register(%s, __lip_fn_%s(host))\n", quote(fn.Name), fn.Name)
		}
	}
	for _, n := range g.Nodes {
		if n.FeedbackAttempts > 0 {
			call, ok := n.Expr.(*ast.CallExpr)
			if !ok || len(call.Args) != 4 {
				return "", fmt.Errorf("node %s: invalid feedback expression", n.Name)
			}
			initial, ok := call.Args[0].(*ast.CallExpr)
			if !ok {
				return "", fmt.Errorf("node %s: feedback initial expression must be a call", n.Name)
			}
			fmt.Fprintf(&b, "\tg.Add(runtime.NodeSpec{Name: %s, Pure: false, Deps: %s, Gates: %s, Feedback: &runtime.FeedbackSpec{Attempts: %d, Init: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {\n", quote(n.Name), stringSlice(n.Deps), stringSlice(n.Gates), n.FeedbackAttempts)
			expr, err := emitExpr(initial)
			if err != nil {
				return "", fmt.Errorf("node %s: %w", n.Name, err)
			}
			b.WriteString(expr)
			fmt.Fprintf(&b, "\n\t}, Step: func(ctx context.Context, current runtime.Value) runtime.Result { return host.Call(ctx, %s, []runtime.Value{current}) }, Verify: func(ctx context.Context, current runtime.Value) runtime.Result { return host.Call(ctx, %s, []runtime.Value{current}) }},", quote(n.FeedbackStep), quote(n.FeedbackVerify))
			if len(n.Gates) > 0 {
				b.WriteString(" Gate: func(values map[string]runtime.Value) (bool, error) {\n")
				for _, gate := range n.Gates {
					fmt.Fprintf(&b, "\t\tok, err := runtime.Bool(values[%s]); if err != nil { return false, err }; if !ok { return false, nil }\n", quote(gate))
				}
				b.WriteString("\t\treturn true, nil\n\t},")
			}
			if n.Output {
				b.WriteString(" Output: true,")
			}
			b.WriteString("})\n")
			continue
		}
		if n.RetryAttempts > 0 {
			call, ok := n.Expr.(*ast.CallExpr)
			if !ok || len(call.Args) != 2 {
				return "", fmt.Errorf("node %s: invalid retry expression", n.Name)
			}
			inner, ok := call.Args[0].(*ast.CallExpr)
			if !ok {
				return "", fmt.Errorf("node %s: retry first argument must be a call", n.Name)
			}
			fmt.Fprintf(&b, "\tg.Add(runtime.NodeSpec{Name: %s, Op: %s, Pure: false, Deps: %s, Gates: %s, Retry: &runtime.RetrySpec{Attempts: %d, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {\n", quote(n.Name), quote(inner.Name), stringSlice(n.Deps), stringSlice(n.Gates), n.RetryAttempts)
			expr, err := emitExpr(inner)
			if err != nil {
				return "", fmt.Errorf("node %s: %w", n.Name, err)
			}
			b.WriteString(expr)
			b.WriteString("\n\t}},")
			if len(n.Gates) > 0 {
				b.WriteString(" Gate: func(values map[string]runtime.Value) (bool, error) {\n")
				for _, gate := range n.Gates {
					fmt.Fprintf(&b, "\t\tok, err := runtime.Bool(values[%s]); if err != nil { return false, err }; if !ok { return false, nil }\n", quote(gate))
				}
				b.WriteString("\t\treturn true, nil\n\t},")
			}
			if n.Output {
				b.WriteString(" Output: true,")
			}
			b.WriteString("})\n")
			continue
		}
		if n.State {
			call, ok := n.Expr.(*ast.CallExpr)
			if !ok || len(call.Args) != 1 {
				return "", fmt.Errorf("node %s: invalid state expression", n.Name)
			}
			fmt.Fprintf(&b, "\tg.Add(runtime.NodeSpec{Name: %s, Pure: true, State: true, Deps: %s, Gates: %s, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {\n", quote(n.Name), stringSlice(n.Deps), stringSlice(n.Gates))
			expr, err := emitExpr(call.Args[0])
			if err != nil {
				return "", fmt.Errorf("node %s: %w", n.Name, err)
			}
			b.WriteString(expr)
			b.WriteString("\n\t},")
			if len(n.Gates) > 0 {
				b.WriteString(" Gate: func(values map[string]runtime.Value) (bool, error) {\n")
				for _, gate := range n.Gates {
					fmt.Fprintf(&b, "\t\tok, err := runtime.Bool(values[%s]); if err != nil { return false, err }; if !ok { return false, nil }\n", quote(gate))
				}
				b.WriteString("\t\treturn true, nil\n\t},")
			}
			if n.Output {
				b.WriteString(" Output: true,")
			}
			b.WriteString("})\n")
			continue
		}
		if comp, ok := n.Expr.(*ast.ComprehensionExpr); ok {
			source, sourceOK := comp.Source.(*ast.IdentExpr)
			if !sourceOK {
				return "", fmt.Errorf("node %s: comprehension source must be an identifier", n.Name)
			}
			ops := callNames(comp.Element)
			pure := len(ops) == 0
			fmt.Fprintf(&b, "\tg.Add(runtime.NodeSpec{Name: %s, Pure: %t, Deps: %s, Gates: %s, Map: &runtime.MapSpec{Source: %s, Pure: %t, Ops: %s, Eval: func(ctx context.Context, item runtime.Value, values map[string]runtime.Value) runtime.Result {\n", quote(n.Name), pure, stringSlice(n.Deps), stringSlice(n.Gates), quote(source.Name), pure, stringSlice(ops))
			expr, err := emitMapElement(comp)
			if err != nil {
				return "", fmt.Errorf("node %s: %w", n.Name, err)
			}
			b.WriteString(expr)
			b.WriteString("\n\t}},")
			if len(n.Gates) > 0 {
				b.WriteString(" Gate: func(values map[string]runtime.Value) (bool, error) {\n")
				for _, gate := range n.Gates {
					fmt.Fprintf(&b, "\t\tok, err := runtime.Bool(values[%s]); if err != nil { return false, err }; if !ok { return false, nil }\n", quote(gate))
				}
				b.WriteString("\t\treturn true, nil\n\t},")
			}
			if n.Output {
				b.WriteString(" Output: true,")
			}
			b.WriteString("})\n")
			continue
		}
		callName := ""
		pure := true
		if call, ok := n.Expr.(*ast.CallExpr); ok {
			callName = call.Name
			pure = false
		}
		fmt.Fprintf(&b, "\tg.Add(runtime.NodeSpec{Name: %s, Op: %s, Pure: %t, Deps: %s, Gates: %s, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {\n", quote(n.Name), quote(callName), pure, stringSlice(n.Deps), stringSlice(n.Gates))
		expr, err := emitExpr(n.Expr)
		if err != nil {
			return "", fmt.Errorf("node %s: %w", n.Name, err)
		}
		b.WriteString(expr)
		b.WriteString("\n\t},")
		if len(n.Gates) > 0 {
			b.WriteString(" Gate: func(values map[string]runtime.Value) (bool, error) {\n")
			for _, gate := range n.Gates {
				fmt.Fprintf(&b, "\t\tok, err := runtime.Bool(values[%s]); if err != nil { return false, err }; if !ok { return false, nil }\n", quote(gate))
			}
			b.WriteString("\t\treturn true, nil\n\t},")
		}
		if n.Output {
			b.WriteString(" Output: true,")
		}
		b.WriteString("})\n")
	}
	b.WriteString("\treturn g\n}\n\n")
	b.WriteString("func checkInputs(inputs map[string]runtime.Value) error {\n")
	for _, param := range g.Params {
		fmt.Fprintf(&b, "\tif _, ok := inputs[%s]; !ok { return fmt.Errorf(\"missing flow input %s\") }\n", quote(param), param)
		if typ := gParamType(g, param); typ != "any" {
			fmt.Fprintf(&b, "\tif err := runtime.CheckType(inputs[%s], %s); err != nil { return fmt.Errorf(\"input %s: %%w\", err) }\n", quote(param), quote(typ), param)
		}
	}
	b.WriteString("\treturn nil\n}\n\n")
	b.WriteString("type Instance struct { engine *runtime.Instance }\n\n")
	b.WriteString("func NewInstance(host runtime.Host, inputs map[string]runtime.Value) (*Instance, error) { if err := checkInputs(inputs); err != nil { return nil, err }; graph := buildGraph(host); return &Instance{engine: graph.NewInstance(host, inputs)}, nil }\n\n")
	b.WriteString("func (i *Instance) Tick(ctx context.Context, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) { if i == nil || i.engine == nil { return nil, nil, fmt.Errorf(\"nil flow instance\") }; return i.engine.Tick(ctx, inputs) }\n\n")
	b.WriteString("func (i *Instance) SetState(name string, value runtime.Value) error { if i == nil || i.engine == nil { return fmt.Errorf(\"nil flow instance\") }; return i.engine.SetState(name, value) }\n\n")
	b.WriteString("func (i *Instance) State(name string) (runtime.Value, bool) { if i == nil || i.engine == nil { return nil, false }; return i.engine.State(name) }\n\n")
	b.WriteString("func (i *Instance) TickCount() uint64 { if i == nil || i.engine == nil { return 0 }; return i.engine.TickCount() }\n\n")
	b.WriteString("func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) { if err := checkInputs(inputs); err != nil { return nil, nil, err }; return buildGraph(host).RunAuto(ctx, host, inputs) }\n\n")
	b.WriteString("func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) { if err := checkInputs(inputs); err != nil { return nil, nil, err }; return buildGraph(host).Run(ctx, inputs) }\n\n")
	b.WriteString("func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) { if err := checkInputs(inputs); err != nil { return nil, nil, err }; return buildGraph(host).RunParallel(ctx, host, inputs, limit) }\n")
	if options.IncludeMain {
		b.WriteString("\nfunc main() {\n\tctx := context.Background()\n\thost := runtime.DefaultHost()\n\tinputs := map[string]runtime.Value{}\n")
		for index, param := range g.Params {
			fmt.Fprintf(&b, "\tinputs[%s] = sampleInput(%s, %d)\n", quote(param), quote(gParamType(g, param)), index)
		}
		b.WriteString("\tvalue, trace, err := Run(ctx, host, inputs)\n")
		b.WriteString("\tif err != nil { fmt.Println(\"error:\", err); for _, event := range trace { fmt.Printf(\"%s %s %s\\n\", event.Node, event.Status, event.Reason) }; os.Exit(1) }\n")
		b.WriteString("\tfmt.Println(value)\n}\n")
	}
	return b.String(), nil
}

func emitExpr(expr ast.Expr) (string, error) {
	ident := func(name string) string { return fmt.Sprintf("values[%s]", quote(name)) }
	emitter := newValueEmitter(ident, "\t\t")
	return emitResultExpr(expr, emitter)
}

func emitMapElement(comp *ast.ComprehensionExpr) (string, error) {
	ident := func(name string) string {
		if name == comp.Variable {
			return "item"
		}
		return fmt.Sprintf("values[%s]", quote(name))
	}
	emitter := newValueEmitter(ident, "\t\t\t")
	return emitResultExpr(comp.Element, emitter)
}

func emitResultExpr(expr ast.Expr, emitter *valueEmitter) (string, error) {
	if call, ok := expr.(*ast.CallExpr); ok {
		args := make([]string, len(call.Args))
		for i, arg := range call.Args {
			value, err := emitter.value(arg)
			if err != nil {
				return "", err
			}
			args[i] = value
		}
		emitter.line("return host.Call(ctx, %s, []runtime.Value{%s})", quote(call.Name), strings.Join(args, ", "))
		return emitter.code(), nil
	}
	value, err := emitter.value(expr)
	if err != nil {
		return "", err
	}
	emitter.line("return runtime.Ready(%s)", value)
	return emitter.code(), nil
}

type valueEmitter struct {
	lines  *[]string
	next   *int
	indent string
	ident  func(string) string
}

func newValueEmitter(ident func(string) string, indent string) *valueEmitter {
	lines := []string{}
	next := 0
	return &valueEmitter{lines: &lines, next: &next, indent: indent, ident: ident}
}

func (e *valueEmitter) child(indent string) *valueEmitter {
	return &valueEmitter{lines: e.lines, next: e.next, indent: indent, ident: e.ident}
}

func (e *valueEmitter) line(format string, args ...any) {
	*e.lines = append(*e.lines, e.indent+fmt.Sprintf(format, args...))
}

func (e *valueEmitter) temp() string {
	name := fmt.Sprintf("value%d", *e.next)
	*e.next = *e.next + 1
	return name
}

func (e *valueEmitter) code() string { return strings.Join(*e.lines, "\n") }

func (e *valueEmitter) value(expr ast.Expr) (string, error) {
	switch x := expr.(type) {
	case *ast.LiteralExpr:
		return literal(x.Value), nil
	case *ast.IdentExpr:
		return e.ident(x.Name), nil
	case *ast.BinaryExpr:
		left, err := e.value(x.Left)
		if err != nil {
			return "", err
		}
		right, err := e.value(x.Right)
		if err != nil {
			return "", err
		}
		value := e.temp()
		e.line("%s, err := runtime.Binary(%s, %s, %s)", value, quote(x.Op), left, right)
		e.line("if err != nil { return runtime.Failed(err) }")
		return value, nil
	case *ast.ListExpr:
		items := make([]string, len(x.Items))
		for i, item := range x.Items {
			value, err := e.value(item)
			if err != nil {
				return "", err
			}
			items[i] = value
		}
		return "[]runtime.Value{" + strings.Join(items, ", ") + "}", nil
	case *ast.FieldExpr:
		object, err := e.value(x.Object)
		if err != nil {
			return "", err
		}
		value := e.temp()
		e.line("%s, err := runtime.Field(%s, %s)", value, object, quote(x.Name))
		e.line("if err != nil { return runtime.Failed(err) }")
		return value, nil
	case *ast.IndexExpr:
		object, err := e.value(x.Object)
		if err != nil {
			return "", err
		}
		index, err := e.value(x.Index)
		if err != nil {
			return "", err
		}
		value := e.temp()
		e.line("%s, err := runtime.Index(%s, %s)", value, object, index)
		e.line("if err != nil { return runtime.Failed(err) }")
		return value, nil
	case *ast.IfExpr:
		cond, ok := x.Cond.(*ast.IdentExpr)
		if !ok {
			return "", fmt.Errorf("if condition must be an identifier")
		}
		value := e.temp()
		e.line("var %s runtime.Value", value)
		e.line("ok, err := runtime.Bool(%s)", e.ident(cond.Name))
		e.line("if err != nil { return runtime.Failed(err) }")
		e.line("if ok {")
		thenEmitter := e.child(e.indent + "\t")
		thenValue, err := thenEmitter.value(x.Then)
		if err != nil {
			return "", err
		}
		thenEmitter.line("%s = %s", value, thenValue)
		e.line("} else {")
		elseEmitter := e.child(e.indent + "\t")
		elseValue, err := elseEmitter.value(x.Else)
		if err != nil {
			return "", err
		}
		elseEmitter.line("%s = %s", value, elseValue)
		e.line("}")
		return value, nil
	default:
		return "", fmt.Errorf("unsupported expression %T", expr)
	}
}

func emitFunction(fn *ast.Function) (string, error) {
	params := make(map[string]int, len(fn.Params))
	for i, param := range fn.Params {
		params[param] = i
	}
	ident := func(name string) string { return fmt.Sprintf("args[%d]", params[name]) }
	var b strings.Builder
	fmt.Fprintf(&b, "func __lip_fn_%s(host runtime.Host) runtime.Op {\n", fn.Name)
	b.WriteString("\treturn func(ctx context.Context, args []runtime.Value) runtime.Result {\n")
	fmt.Fprintf(&b, "\t\tif len(args) != %d { return runtime.Failed(fmt.Errorf(\"function %s expects %d arguments, got %%d\", len(args))) }\n", len(fn.Params), fn.Name, len(fn.Params))
	for i, param := range fn.Params {
		if typ := gFunctionParamType(fn, param); typ != "any" {
			fmt.Fprintf(&b, "\t\tif err := runtime.CheckType(args[%d], %s); err != nil { return runtime.Failed(fmt.Errorf(\"argument %s: %%w\", err)) }\n", i, quote(typ), param)
		}
	}
	switch e := fn.Return.(type) {
	case *ast.CallExpr:
		args := make([]string, len(e.Args))
		emitter := newValueEmitter(ident, "\t\t")
		for i, arg := range e.Args {
			value, err := emitter.value(arg)
			if err != nil {
				return "", err
			}
			args[i] = value
		}
		if code := emitter.code(); code != "" {
			b.WriteString(code)
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "\t\treturn host.Call(ctx, %s, []runtime.Value{%s})\n", quote(e.Name), strings.Join(args, ", "))
	default:
		emitter := newValueEmitter(ident, "\t\t")
		value, err := emitter.value(fn.Return)
		if err != nil {
			return "", fmt.Errorf("function %s: %w", fn.Name, err)
		}
		if code := emitter.code(); code != "" {
			b.WriteString(code)
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "\t\treturn runtime.Ready(%s)\n", value)
	}
	b.WriteString("\t}\n}\n")
	return b.String(), nil
}

func functionIsPure(fn *ast.Function) bool { return !containsCall(fn.Return) }

func containsCall(expr ast.Expr) bool {
	switch e := expr.(type) {
	case *ast.CallExpr:
		return true
	case *ast.BinaryExpr:
		return containsCall(e.Left) || containsCall(e.Right)
	case *ast.IfExpr:
		return containsCall(e.Cond) || containsCall(e.Then) || containsCall(e.Else)
	case *ast.ListExpr:
		for _, item := range e.Items {
			if containsCall(item) {
				return true
			}
		}
	case *ast.ComprehensionExpr:
		return containsCall(e.Element) || containsCall(e.Source)
	case *ast.FieldExpr:
		return containsCall(e.Object)
	case *ast.IndexExpr:
		return containsCall(e.Object) || containsCall(e.Index)
	}
	return false
}

func callNames(expr ast.Expr) []string {
	seen := map[string]bool{}
	var names []string
	var visit func(ast.Expr)
	visit = func(e ast.Expr) {
		switch x := e.(type) {
		case *ast.CallExpr:
			if !seen[x.Name] {
				seen[x.Name] = true
				names = append(names, x.Name)
			}
			for _, arg := range x.Args {
				visit(arg)
			}
		case *ast.BinaryExpr:
			visit(x.Left)
			visit(x.Right)
		case *ast.IfExpr:
			visit(x.Cond)
			visit(x.Then)
			visit(x.Else)
		case *ast.ListExpr:
			for _, item := range x.Items {
				visit(item)
			}
		case *ast.ComprehensionExpr:
			visit(x.Element)
			visit(x.Source)
		case *ast.FieldExpr:
			visit(x.Object)
		case *ast.IndexExpr:
			visit(x.Object)
			visit(x.Index)
		}
	}
	visit(expr)
	return names
}

func literal(v any) string {
	switch x := v.(type) {
	case string:
		return "runtime.Value(" + quote(x) + ")"
	case bool:
		if x {
			return "runtime.Value(true)"
		}
		return "runtime.Value(false)"
	case float64:
		return fmt.Sprintf("runtime.Value(%s)", strconv.FormatFloat(x, 'f', -1, 64))
	default:
		return "runtime.Value(nil)"
	}
}

func stringSlice(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = quote(v)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func quote(s string) string { return strconv.Quote(s) }

func gParamType(g *Graph, name string) string {
	if g.ParamTypes != nil {
		if typ := g.ParamTypes[name]; typ != "" {
			return typ
		}
	}
	return "any"
}

func gFunctionParamType(fn *ast.Function, name string) string {
	if fn.ParamTypes != nil {
		if typ := fn.ParamTypes[name]; typ != "" {
			return typ
		}
	}
	return "any"
}
