// editor-catalog generates spelling data shared by the native editor packages.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"lipalpha/compiler/lexer"
	"lipalpha/compiler/token"
	"lipalpha/internal/listops"
	"lipalpha/internal/stringops"
	"lipalpha/runtime"
)

type catalog struct {
	Version   string   `json:"version"`
	Keywords  []string `json:"keywords"`
	Types     []string `json:"types"`
	Builtins  []string `json:"builtins"`
	Operators []string `json:"operators"`
}

func language() catalog {
	c := catalog{Version: runtime.Version, Types: []string{"any", "bool", "list", "number", "object", "string", "void"},
		Builtins: []string{"str", "len", "range", "fold", "fail", "print", "state", "retry", "feedback", "python.call", "python.getattr", "python.to_json", "python.release", "python.module_available", "python.open_blob", "python.put_blob", "python.release_blob"}}
	// Discover reserved words through the actual lexer rather than maintaining
	// a second keyword list. Token spellings also supply every language operator.
	for kind := token.Ident; kind <= token.Continue; kind++ {
		word := kind.String()
		if word == "unknown" {
			continue
		}
		tokens, err := lexer.New(word).Lex()
		if err != nil || len(tokens) != 2 || tokens[0].Kind != kind {
			continue
		}
		if word[0] >= 'a' && word[0] <= 'z' {
			if kind != token.Ident {
				c.Keywords = append(c.Keywords, word)
			}
		} else if !strings.ContainsAny(word, "(){}[],;:.") {
			c.Operators = append(c.Operators, word)
		}
	}
	for _, spec := range listops.All() {
		c.Builtins = append(c.Builtins, spec.Name)
	}
	for _, spec := range stringops.All() {
		c.Builtins = append(c.Builtins, spec.Name)
	}
	sort.Strings(c.Keywords)
	sort.Strings(c.Builtins)
	sort.Strings(c.Operators)
	return c
}

func quoted(words []string, quote func(string) string) string {
	result := make([]string, len(words))
	for i, word := range words {
		result[i] = quote(word)
	}
	return strings.Join(result, " ")
}

func outputs(c catalog) map[string][]byte {
	data, _ := json.MarshalIndent(c, "", "  ")
	vim := fmt.Sprintf("vim9script\n# Generated by scripts/editor-catalog; LIP %s. DO NOT EDIT.\n", c.Version)
	lua := fmt.Sprintf("-- Generated by scripts/editor-catalog; LIP %s. DO NOT EDIT.\nreturn {\n  version = %s,\n", c.Version, strconv.Quote(c.Version))
	for _, item := range []struct {
		name  string
		words []string
	}{{"keywords", c.Keywords}, {"types", c.Types}, {"builtins", c.Builtins}, {"operators", c.Operators}} {
		items := make([]string, len(item.words))
		luaItems := make([]string, len(item.words))
		for i, word := range item.words {
			items[i] = "'" + strings.ReplaceAll(word, "'", "''") + "'"
			luaItems[i] = strconv.Quote(word)
		}
		vim += fmt.Sprintf("export def %s(): list<string>\n  return [%s]\nenddef\n\n", strings.ToUpper(item.name[:1])+item.name[1:], strings.Join(items, ", "))
		lua += fmt.Sprintf("  %s = { %s },\n", item.name, strings.Join(luaItems, ", "))
	}
	lua += "}\n"
	elisp := fmt.Sprintf(";;; lip-keywords.el --- Generated LIP %s spelling data -*- lexical-binding: t; -*-\n;;; Generated by scripts/editor-catalog; DO NOT EDIT.\n", c.Version)
	elisp += fmt.Sprintf("(defconst lip-language-version %s)\n", strconv.Quote(c.Version))
	for _, item := range []struct {
		name  string
		words []string
	}{{"keywords", c.Keywords}, {"types", c.Types}, {"builtins", c.Builtins}, {"operators", c.Operators}} {
		elisp += fmt.Sprintf("(defconst lip-language-%s '(%s))\n", item.name, quoted(item.words, strconv.Quote))
	}
	elisp += "(provide 'lip-keywords)\n;;; lip-keywords.el ends here\n"
	return map[string][]byte{"editors/lip-language.json": append(data, '\n'), "editors/vim/autoload/lip/catalog.vim": []byte(vim), "editors/neovim/lua/lip/catalog.lua": []byte(lua), "editors/emacs/lip-keywords.el": []byte(elisp)}
}

func main() {
	check := flag.Bool("check", false, "check generated editor data without writing")
	root := flag.String("root", ".", "repository root")
	flag.Parse()
	for path, data := range outputs(language()) {
		path = filepath.Join(*root, path)
		if *check {
			existing, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(existing, data) {
				fmt.Fprintf(os.Stderr, "regenerate %s: go run ./scripts/editor-catalog\n", path)
				os.Exit(1)
			}
		} else {
			if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
				panic(err)
			}
			if err := os.WriteFile(path, data, 0644); err != nil {
				panic(err)
			}
		}
	}
}
