// Code generated by lipc; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"lipalpha/runtime"
)

type Dependency struct {
	Kind  string
	Spec  string
	Alias string
}

func RequiredDependencies() []Dependency { return []Dependency{} }

func parseCLIInputs(args []string) (map[string]runtime.Value, error) {
	inputs, err := runtime.ParseCLIInputs(args, []runtime.Input{})
	if err != nil {
		return nil, fmt.Errorf("%w\nusage: %s", err, os.Args[0])
	}
	return inputs, nil
}

func __lip_fn_twice(host runtime.Host) runtime.Op {
	return func(ctx context.Context, args []runtime.Value) runtime.Result {
		ctx, err := runtime.EnterFunction(ctx)
		if err != nil {
			return runtime.Failed(err)
		}
		if len(args) != 1 {
			return runtime.Failed(fmt.Errorf("function twice expects 1 arguments, got %d", len(args)))
		}
		if err := runtime.CheckType(args[0], "number"); err != nil {
			return runtime.Failed(fmt.Errorf("argument x: %w", err))
		}
		value0, err := runtime.Binary("*", args[0], runtime.Value(float64(2)))
		if err != nil {
			return runtime.Failed(err)
		}
		if err := runtime.CheckType(value0, "number"); err != nil {
			return runtime.Failed(fmt.Errorf("function twice result: %w", err))
		}
		return runtime.Ready(value0)
	}
}

func buildGraph(host runtime.Host) *runtime.Graph {
	host = host.Clone()
	g := runtime.NewGraph()
	host.RegisterPure("twice", __lip_fn_twice(host))
	g.Add(runtime.NodeSpec{Name: "values", Op: "", Effect: runtime.EffectPure, Deps: nil, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return runtime.Ready([]runtime.Value{runtime.Value(float64(1)), runtime.Value(float64(2)), runtime.Value(float64(3)), runtime.Value(float64(4))})
	}})
	g.Add(runtime.NodeSpec{Name: "doubled", Effect: runtime.EffectPure, Deps: []string{"values"}, Gates: nil, Map: &runtime.MapSpec{Source: "values", Ops: []string{"twice"}, Eval: func(ctx context.Context, item runtime.Value, values map[string]runtime.Value) runtime.Result {
		return host.Call(ctx, "twice", []runtime.Value{item})
	}}})
	g.Add(runtime.NodeSpec{Name: "__return_0", Op: "", Effect: runtime.EffectPure, Deps: []string{"doubled"}, Gates: nil, Eval: func(ctx context.Context, values map[string]runtime.Value) runtime.Result {
		return runtime.Ready(values["doubled"])
	}, Output: true, ValueType: "any"})
	return g
}

func checkInputUpdates(inputs map[string]runtime.Value) error {
	for name, value := range inputs {
		_ = value
		switch name {
		default:
			return fmt.Errorf("unknown flow input %q", name)
		}
	}
	return nil
}

func checkInputs(inputs map[string]runtime.Value) error {
	return checkInputUpdates(inputs)
}

func checkHost(host runtime.Host) error {
	return nil
}

type Instance struct{ engine *runtime.Instance }

func NewInstance(host runtime.Host, inputs map[string]runtime.Value) (*Instance, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, err
	}
	graph := buildGraph(host)
	return &Instance{engine: graph.NewInstance(host, inputs)}, nil
}

func (i *Instance) Tick(ctx context.Context, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if i == nil || i.engine == nil {
		return nil, nil, fmt.Errorf("nil flow instance")
	}
	if err := checkInputUpdates(inputs); err != nil {
		return nil, nil, err
	}
	return i.engine.Tick(ctx, inputs)
}

func (i *Instance) SetState(name string, value runtime.Value) error {
	if i == nil || i.engine == nil {
		return fmt.Errorf("nil flow instance")
	}
	return i.engine.SetState(name, value)
}

func (i *Instance) State(name string) (runtime.Value, bool) {
	if i == nil || i.engine == nil {
		return nil, false
	}
	return i.engine.State(name)
}

func (i *Instance) TickCount() uint64 {
	if i == nil || i.engine == nil {
		return 0
	}
	return i.engine.TickCount()
}

func Run(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunAuto(ctx, host, inputs)
}

func RunSequential(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).Run(ctx, inputs)
}

func RunParallel(ctx context.Context, host runtime.Host, inputs map[string]runtime.Value, limit int) (runtime.Value, []runtime.TraceEvent, error) {
	if err := checkInputs(inputs); err != nil {
		return nil, nil, err
	}
	if err := checkHost(host); err != nil {
		return nil, nil, err
	}
	return buildGraph(host).RunParallel(ctx, host, inputs, limit)
}

func executionError(err error, trace []runtime.TraceEvent) error {
	message, context := err.Error(), ""
	for _, event := range trace {
		if event.Status != runtime.Error {
			continue
		}
		switch event.Node {
		case "values":
			message = "examples/map.lip:4:5: " + event.Reason
			context = "\n  4 |     values = [1, 2, 3, 4]\n    |     ^"
		case "doubled":
			message = "examples/map.lip:5:5: " + event.Reason
			context = "\n  5 |     doubled = [twice(x) for x in values]\n    |     ^"
		case "__return_0":
			message = "examples/map.lip:6:5: " + event.Reason
			context = "\n  6 |     return doubled\n    |     ^"
		}
		break
	}
	if hint := runtime.ExecutionHint(err); hint != "" {
		context += "\n  hint: " + hint
	}
	return fmt.Errorf("%s%s", message, context)
}

func main() { os.Exit(runMain()) }

func runMain() int {
	inputs, err := parseCLIInputs(os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 2
	}
	_ = inputs
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	host := runtime.DefaultHost()
	value, trace, err := Run(ctx, host, inputs)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", executionError(err, trace))
		return 1
	}
	output, err := runtime.FormatValue(value)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	fmt.Println(output)
	return 0
}
