vim9script
# Generated by scripts/editor-catalog; LIP 0.6.3. DO NOT EDIT.
export def Keywords(): list<string>
  return ['as', 'break', 'continue', 'else', 'false', 'flow', 'fn', 'for', 'if', 'import', 'in', 'match', 'null', 'return', 'true']
enddef

export def Types(): list<string>
  return ['any', 'bool', 'list', 'number', 'object', 'string', 'void']
enddef

export def Builtins(): list<string>
  return ['fail', 'feedback', 'fold', 'len', 'list.all', 'list.any', 'list.append', 'list.cartesian', 'list.concat', 'list.contains', 'list.count', 'list.drop', 'list.enumerate', 'list.filter', 'list.first', 'list.flatten', 'list.group', 'list.group_by', 'list.last', 'list.map', 'list.max', 'list.min', 'list.partition', 'list.prepend', 'list.product', 'list.repeat', 'list.reverse', 'list.riffle', 'list.scan', 'list.slice', 'list.sort', 'list.sort_by', 'list.split_by', 'list.sum', 'list.take', 'list.transpose', 'list.unique', 'list.zip', 'print', 'python.call', 'python.getattr', 'python.module_available', 'python.open_blob', 'python.put_blob', 'python.release', 'python.release_blob', 'python.to_json', 'range', 'retry', 'state', 'str', 'string.chars', 'string.contains', 'string.count', 'string.ends_with', 'string.find', 'string.join', 'string.lines', 'string.lower', 'string.parse_number', 'string.repeat', 'string.replace', 'string.slice', 'string.split', 'string.split_whitespace', 'string.starts_with', 'string.trim', 'string.trim_end', 'string.trim_start', 'string.upper']
enddef

export def Operators(): list<string>
  return ['!', '!=', '%', '&&', '*', '**', '*/', '+', '-', '->', '/', '//', '<', '<=', '=', '==', '=>', '>', '>=', '?', '||']
enddef

